feat: provision and use mTLS credentials
Kong/gateway-operator pull request #103
Opened 2022-07-22 22:06 UTC by rainest

**What this PR does / why we need it**:
Adds mTLS authentication between ControlPlanes and DataPlanes using the functionality provided by https://github.com/Kong/kubernetes-ingress-controller/pull/2148

**Which issue this PR fixes** fix #7 

**Special notes for your reviewer**:
- The subject for the ControlPlane certificate is an arbitrary example. Is there something we _should_ be using here? All the nginx side will care about is that it's signed by the CA; it has no expectation for the subject.
- This lacks any handling of certificate rotation. This seems like something we'll need but that is large enough to require its own spike about exactly how to handle it.
- With the expectation that DataPlanes and ControlPlanes can reside in any namespace, and that we need to check for existing certificates, this requires a cluster-wide Secret Get permission. Is there any way we can avoid this?
- The user-provided cluster CA Secret must live in the operator's namespace, which is hard-coded right now. Do we have any existing tooling to retrieve this (our own or something in controller-runtime)? I've hardcoded `kong-system` for now.
- Although the original issue includes it in requirements, this does not implement deletion because there's currently no deletion handling in the reconcilers at all. Why was that missing? Is cleanup in general tracked elsewhere?

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect significant changes

2022-07-23 15:48 UTC, jrsmroz commented on controllers/controlplane_controller_utils.go
> +	}
Should anyone be able to overwrite those env vars?  We had some discussion with @shaneutt , and basically how we handle env vars in operator should change. Some vars should be setable only by an operator.

2022-07-25 13:53 UTC, shaneutt commented on controllers/controlplane_controller_utils.go
> +	}
That is covered by https://github.com/Kong/gateway-operator/issues/65, I do think it's OK for this PR to continue doing things the way they've been done, as long as we reflect the need to update the things added here in https://github.com/Kong/gateway-operator/issues/65 as well so they get resolved.

2022-07-25 18:20 UTC, rainest commented on controllers/controlplane_controller_utils.go
> +	}
Allowing user overrides of anything is generally good: we can't reliably know every reason someone might want to override our default behavior (e.g. there's a decent case for allowing overrides here to let users issue certs from their own CA infrastructure, since they may want to enforce controls our built-in CA doesn't expose) and allowing arbitrary overrides lets them do so with a simple UX (you just set the variable) and without any code change on our part.

This approach has worked well in the chart. It's quite rare for users to be over-eager and break installs by setting environment variables they think they need, unaware of the automation that would correctly set it.

I do think we need to [change the form of this](https://github.com/Kong/gateway-operator/issues/46), since the current code for checking overrides is awkward, but we should keep the ability for overrides even if we don't think users _should_ need them.

2022-07-26 23:47 UTC, rainest commented
Nothing much on the draft version, so handled some of the simpler items and marking it ready to try and force the others.

2022-07-27 14:54 UTC, shaneutt requested changes
The vast majority of this looks great, the code is very clear and understandable and most of my comments are nitpicks. I do however have a larger concern about CA management I would like to make sure we discuss before we merge this.

2022-07-27 14:54 UTC, shaneutt commented on controllers/controlplane_controller_reconciler_utils.go
> +	created, err := maybeCreateCertificateSecret(ctx, fmt.Sprintf("%s.%s", controlplane.Name, controlplane.Namespace),
nit: "maybe" do something can be a bit vague, but if what we're really doing is either GET or PUT, perhaps:

```suggestion
	created, err := getOrCreateCertificateSecret(ctx, fmt.Sprintf("%s.%s", controlplane.Name, controlplane.Namespace),
```

2022-07-27 14:54 UTC, shaneutt commented on controllers/dataplane_controller_reconciler_utils.go
> +	created, err := maybeCreateCertificateSecret(ctx, fmt.Sprintf("%s.%s.svc", serviceName, dataplane.Namespace),
```suggestion
	created, err := getOrCreateCertificateSecret(ctx, fmt.Sprintf("%s.%s.svc", serviceName, dataplane.Namespace),
```

2022-07-27 14:54 UTC, shaneutt commented on go.mod
wow that's a lot of dependencies added.

2022-07-27 14:54 UTC, shaneutt commented on main.go
> +		ClusterCASecret: clusterCASecret,
So if I'm reading this right, we're effectively _requiring_ that the end-user provides the CA certificate for mTLS connectivity. The intention (if not the letter) of https://github.com/Kong/gateway-operator/issues/7 was to fill in this blank if left empty: it should be the case that a default deployment of the Gateway Operator is capable of setting up mTLS between `ControlPlane` and `DataPlane` objects _all by itself_. So I have a couple questions:

- am I understanding correctly that we don't have this yet, or did I miss something?
- if I am understanding correctly, doesn't this result in the currently `kubectl apply` method of deployment in the README resulting in an operator that doesn't function properly?

2022-07-27 16:52 UTC, rainest commented on controllers/controlplane_controller_reconciler_utils.go
> +	created, err := maybeCreateCertificateSecret(ctx, fmt.Sprintf("%s.%s", controlplane.Name, controlplane.Namespace),
We've used it elsewhere, e.g. https://github.com/Kong/kubernetes-ingress-controller/blob/4a7d27aa4be6bde04b916197b9bdefdc034231f2/internal/manager/controllerdef.go#L48, I think Michal had suggested the convention for functions that may not take action. It's not actually getting anything, just indicating if it did create the certificate, so maybe sounds more appropriate, WDYT?

2022-07-27 19:04 UTC, shaneutt commented on controllers/controlplane_controller_reconciler_utils.go
> +	created, err := maybeCreateCertificateSecret(ctx, fmt.Sprintf("%s.%s", controlplane.Name, controlplane.Namespace),
Sure, and good point. Not a blocker.

2022-07-27 19:04 UTC, shaneutt commented on controllers/dataplane_controller_reconciler_utils.go
> +	created, err := maybeCreateCertificateSecret(ctx, fmt.Sprintf("%s.%s.svc", serviceName, dataplane.Namespace),
Not a blocker, resolve at your discretion.

2022-07-27 22:10 UTC, rainest commented on main.go
> +		ClusterCASecret: clusterCASecret,
#7 doesn't say anything about prereqs or lack thereof :smirk_cat: only that the operator provision and use certificates on creation of ControlPlane and DataPlane! https://github.com/Kong/gateway-operator/pull/103/commits/8489bd5707c6c9489a6dddb3167679a09eb39c2f

Using a Runnable kinda obscures failure handling, and I'm not sure there's a way to test that (or how much we care to), but, for example, changing `maybeCreateCACertificate()` to try and use a non-existent namespace will result in

```
INFO: starting the operator's controller manager
INFO: controller output is being logged to /tmp/gateway-operator-controller-logs1692886461
ERROR: problem running manager: namespaces "dgdgfgd" not found
```

2022-07-29 18:39 UTC, shaneutt reviewed
Thank you for adding the automated CA setup. Overall I think this is looking good. I have mostly minor comments.

2022-07-29 18:39 UTC, shaneutt commented on internal/manager/run.go
> +		serial, err := rand.Int(rand.Reader, big.NewInt(9999999999))
You could avoid the arbitrary literal large number here and just go with the biggest possible maximum value using constants:

```suggestion
		serial, err := rand.Int(rand.Reader, big.NewInt(math.MaxInt64))
```

2022-07-29 18:39 UTC, shaneutt commented on internal/manager/run.go
> +			//DNSNames:           []string{subject},
We should resolve this comment.

2022-07-29 18:39 UTC, shaneutt commented on test/integration/suite_test.go
> +	for i := 0; i < 60; i++ {
I'm not necessarily opposed to this approach, but you could also using a timeout, e.g.:

```golang
timeout := time.Now().Add(time.Minute)
for timeout.After(time.Now()) {
```

This has the benefit of the amount of time you sleep between checks no longer having any bearing on the overall time that is allowed, allowing you to use a sleep as little as `time.Millisecond * 50` or none at all perhaps. A micro-optimization for sure, but just something for you to consider while you're already in here.

2022-07-29 19:05 UTC, rainest commented on internal/manager/run.go
> +		serial, err := rand.Int(rand.Reader, big.NewInt(9999999999))
Thanks, I was looking for that constant in big and concluded that it didn't exist since there was none there.

2022-07-29 19:11 UTC, rainest commented on internal/manager/run.go
> +			//DNSNames:           []string{subject},
Yeah, this was a leftover from copying another template and being unsure if it'd trip the SAN requirement (it doesn't, that's only if the CN is a hostname IIRC).

2022-07-29 19:16 UTC, rainest commented
I'm taking the :heavy_check_mark: as implicit approval of handling rotation in a separate PR. @shaneutt did you have thoughts on the other two open items in the OP, i.e. handling deletion and the additional Secret permissions?

2022-08-01 18:44 UTC, shaneutt commented
> I'm taking the heavy_check_mark as implicit approval of handling rotation in a separate PR. @shaneutt did you have thoughts on the other two open items in the OP, i.e. handling deletion and the additional Secret permissions?

I'm OK with rotation and deletion being handled as separate issues. I might need clarification about the permissions part, if we just mean the permissions needed to manage secrets in this way at all we need those immediately in this PR or a user will have to manually modify the manifests for the operator to work at all.

2022-08-01 23:10 UTC, rainest commented
>  I might need clarification about the permissions part, if we just mean the permissions needed to manage secrets in this way at all we need those immediately in this PR or a user will have to manually modify the manifests for the operator to work at all.

We don't currently have permissions to Secrets. To check if we already have certificates in ControlPlane/DataPlane namespaces (which can be any namespace), we need to add Get permissions, granting access to any Secret. This PR includes modifications that add a role that grants access to all Secrets in all namespaces.

This is a sensitive permission that we'd like to avoid if possible, to decrease attack surface for Secret leaks and ease installation if you don't have cluster-wide Secret permissions yourself. I don't think we can really do that without restricting the namespaces that our Deployments can live in.

Restricting namespaces may be viable (offhand I don't know of a reason they'd need to share a namespace with an application we don't already account for), but absent a single blessed namepace (which would pose problems for multi-tenant installs that shouldn't have access to other tenants' Secrets), isn't something we can immediately do with the existing manifests. You'd need something like the --watch-namespaces+chart role automation or manual kustomize work to update namespaces and duplicate the role.

2022-08-01 23:13 UTC, shaneutt commented
Ok, then I'm :heavy_check_mark: once we have a follow-up issue in place to further discuss and try to reduce the scope of `Secrets` privileges.

2022-08-01 23:39 UTC, rainest commented
Alright, https://github.com/Kong/gateway-operator/issues/121, and deletion?

Unrelated to that, there's apparently some dependency nonsense I need to sort out? Attempting to merge go.sum by stripping merge annotations and tidying resulted in:

```
github.com/kong/gateway-operator/controllers imports
	github.com/cloudflare/cfssl/signer/local imports
	github.com/google/certificate-transparency-go imports
	go.etcd.io/etcd/v3 imports
	go.etcd.io/etcd/tests/v3/integration imports
	go.etcd.io/etcd/pkg/v3/logutil: module go.etcd.io/etcd/pkg/v3@latest found (v3.5.4), but does not contain package go.etcd.io/etcd/pkg/v3/logutil
```

2022-08-02 21:23 UTC, rainest commented
Go had already updated `go.etcd.io/etcd/pkg/v3` and but had not updated and was still trying to use versions of `go.etcd.io/etcd/tests/v3/integration` and such. Getting those outdated packages manually fixed it.

No luck on getting the deletes question answered, it seems, so just gonna mark this ready to merge and figure that out later :shrug:

2022-08-04 14:17 UTC, shaneutt submitted a review, later dismissed

2022-08-05 19:25 UTC, shaneutt approved these changes

2022-08-05 19:25 UTC, merged