fix: always set controlplane default envs
Kong/gateway-operator pull request #105
Opened 2022-07-26 07:39 UTC by randmonkey

**What this PR does / why we need it**:

always set default environment variables for `controlplane` resource, fix the bug that `POD_NAME` and `POD_NAMESPACE` is not set when any `env` specified in `ControlPlane`

**Which issue this PR fixes**

fixes #63

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect significant changes

2022-07-26 13:35 UTC, shaneutt requested changes
Looking good :+1: 

I think we're really close to being able to merge this, however given the context of https://github.com/Kong/gateway-operator/issues/63 it would appear now would be a good time to add something to our tests which proves we've resolved https://github.com/Kong/gateway-operator/issues/63 and helps prevent us from introducing regressions in the future.

I recommend we add (or even just update) an integration tests to validate the behavior of ENV var fulfillment when the user has or has not already provided vars.

2022-07-26 13:35 UTC, shaneutt commented on controllers/controlplane_controller.go
> +	// TODO: add validating here
We need to resolve this TODO or have a follow up issue linked here.

2022-07-27 04:13 UTC, randmonkey commented on controllers/controlplane_controller.go
> +	// TODO: add validating here
linked to #109.

2022-07-27 04:13 UTC, randmonkey commented on controllers/controlplane_controller.go
> +	debug(log, "setting defaults for ControlPlane resource", controlplane)
done.

2022-07-27 13:01 UTC, shaneutt submitted a review, later dismissed

2022-07-29 03:43 UTC, randmonkey commented
Closed this and re-submit in #113 since signing for commits is required.

2022-07-29 03:43 UTC, closed without merging