WIP: ci: add release pipeline
Kong/gateway-operator pull request #119
Opened 2022-08-01 21:17 UTC by jrsmroz

**What this PR does / why we need it**:

**Which issue this PR fixes**

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect significant changes

2022-08-02 19:57 UTC, pmalek commented on .github/workflows/release.yaml
> +        run: make test.e2e
Wouldn't it be beneficial for time efficiency's sake to run 2 jobs separately: 1 for e2e and 1 for integration and require both for publish-release?

2022-08-02 19:57 UTC, pmalek commented on .github/workflows/release.yaml
> +          - [Changelog](https://github.com/Kong/gateway-operator/blob/main/CHANGELOG.md#${{ needs.semver.outputs.major }}${{ needs.semver.outputs.minor }}${{ needs.semver.outputs.patch }})
I don't see the `semver` job having the `patch` output.

2022-08-02 20:31 UTC, jrsmroz commented on .github/workflows/release.yaml
> +        run: make test.e2e
It make sense, I can change that, thought it's not critical, considering release is not run every time.

2022-08-02 20:47 UTC, rainest approved these changes
I also agree that it'd make sense to run E2E in parallel to fail faster if it's going to fail, but it's not critical. Rest looks good.

2022-08-02 21:37 UTC, shaneutt requested changes

2022-08-02 21:37 UTC, shaneutt commented on .github/workflows/release.yaml
> +    - uses: ncipollo/release-action@v1
It seems that we're so commonly finding third party actions which we want to use, but they always give me pause as in a privileged context (such as this where we give that code our `GITHUB_TOKEN`) they represent possible supply chain attack vectors.

The only saving grace I'm aware of here is that I believe the `GITHUB_TOKEN` in these contexts is a limited time window and expires when the run ends, but I would need to verify that by finding the documentation again.

In this case, how problematic is it for us to avoid this dependency so as to not feed it our API token?

2022-08-03 06:54 UTC, jrsmroz commented on .github/workflows/release.yaml
> +    - uses: ncipollo/release-action@v1
Well, it's from KIC, so I guess if we want to change that, we should so in KIC too.

2022-08-03 08:01 UTC, jrsmroz commented
> I also agree that it'd make sense to run E2E in parallel to fail faster if it's going to fail, but it's not critical. Rest looks good.

Ok, two votes, let me change that than.

2022-08-03 09:13 UTC, jrsmroz commented on .github/workflows/release.yaml
> +        run: make test.e2e
Done

2022-08-03 12:52 UTC, pmalek commented on .github/workflows/release.yaml
> +        description: 'The version to release (e.g. v1.2.3)'
Nit: in yaml you don't need to quote a string if it's not a number (just as you have it in other places in this file.

2022-08-03 12:52 UTC, pmalek commented on .github/workflows/release.yaml
> +    needs: [semver, build-push-images, test-integration-current-kubernetes, test-e2e-current-kubernetes]
Nit: In other places we're using arrays where each element is on its own line. Why use a different approach here? IMHO it's a bit more readable when each entry has it's own line + it's clearer on the diff when adding/removing elements. WDYT?

2022-08-03 14:04 UTC, jrsmroz commented on .github/workflows/release.yaml
> +        description: 'The version to release (e.g. v1.2.3)'
ok

2022-08-03 14:05 UTC, jrsmroz commented on .github/workflows/release.yaml
> +    needs: [semver, build-push-images, test-integration-current-kubernetes, test-e2e-current-kubernetes]
That's true. Fixed.

2022-08-03 14:07 UTC, pmalek approved these changes
LGTM 👍

2022-08-03 18:14 UTC, shaneutt approved these changes

2022-08-03 18:14 UTC, shaneutt commented on .github/workflows/release.yaml
> +    - uses: ncipollo/release-action@v1
Given the precedent I wont block. Would you mind creating a issue to follow up on this? If not, I'm happy to make that issue, either way. ty.

2022-08-03 19:19 UTC, jrsmroz commented on .github/workflows/release.yaml
> +    - uses: ncipollo/release-action@v1
I will. Migrating to GitHub owned action seems safer choice. Not sure what was the story behind using ncipollo/release-action@v1

2022-08-03 22:20 UTC, jrsmroz commented on .github/workflows/release.yaml
> +    - uses: ncipollo/release-action@v1
https://github.com/Kong/gateway-operator/issues/128

2022-08-03 22:20 UTC, merged