fix: gc cluster wide resources owned by ControlPlane on delete
Kong/gateway-operator pull request #144
Opened 2022-08-10 07:07 UTC by randmonkey

**What this PR does / why we need it**:

garbage collect cluster wide resources (currently `ClusterRoles`,`ClusterRoleBindings`) owned by controlplanes when they are deleted.

**Which issue this PR fixes**
fixes #67 
**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect significant changes

2022-08-11 07:33 UTC, pmalek requested changes

2022-08-11 07:33 UTC, pmalek commented on test/integration/controlplane_test.go
> +	err = controlplaneClient.Delete(ctx, controlplane.Name, metav1.DeleteOptions{})
Since we're using `require` above this line and those can fail then this line here can never trigger and we'll never delete the control plane, causing garbage to be left in the cluster.

Can we move this up higher then?

2022-08-11 07:33 UTC, pmalek commented on controllers/controlplane_controller_reconciler_utils.go
> +		}
I think we don't want to return here. The reason for this is that (if I understand this right) we want to remove as much as possible, not "fail fast" during removal.

So perhaps we can use something like https://github.com/hashicorp/go-multierror or an alternative and just group errors but at the same time continue execution to remove as much as possible?

2022-08-11 07:39 UTC, mlavacca commented on controllers/controlplane_controller_consts.go
> +	ControlPlaneFinalizerClusterResourcesGC ControlPlaneFinalizer = "gateway-operator.konghq.com/cluster-resource-gc"
Instead of using a single Omni-comprehensive finalizer, I rather think that using a finalizer for each resource type (e.g., `gateway-operator.konghq.com/cleanup-clusterrole`,  `gateway-operator.konghq.com/cleanup-clusterrolebinding`) is more meaningful for what resources are still to be collected and which are left in the cluster. If we pursue this way, in `garbageCollectClusterResources` we should look up for every finalizer before trying to delete the corresponding resource. WDYT?

2022-08-11 07:39 UTC, mlavacca commented on controllers/controlplane_controller_consts.go
> +	ControlPlaneFinalizerClusterResourcesGC ControlPlaneFinalizer = "gateway-operator.konghq.com/cluster-resource-gc"
Furthermore, don't we have the prefix `gateway-operator.konghq.com` already stored in some variable that we can re-use to build the finalizers?

2022-08-11 07:43 UTC, pmalek commented on controllers/controlplane_controller_consts.go
> +type ControlPlaneFinalizer string
What is the purpose for this type? While generally I'd advocate for having separate types I don't see a benefit of using it here. Can you help me understand the reason for this?

2022-08-11 07:48 UTC, randmonkey commented on test/integration/controlplane_test.go
> +	err = controlplaneClient.Delete(ctx, controlplane.Name, metav1.DeleteOptions{})
> Can we move this up higher then?
higher then what?

I don't know what is your expectation here. In integration tests, the whole test cluster would be destroyed after the test finished by default, so we do not care about whether garbage are in the cluster after test finish (no matter passed or failed).

2022-08-11 07:55 UTC, randmonkey commented on controllers/controlplane_controller_consts.go
> +	ControlPlaneFinalizerClusterResourcesGC ControlPlaneFinalizer = "gateway-operator.konghq.com/cluster-resource-gc"
> Furthermore, don't we have the prefix `gateway-operator.konghq.com` already stored in some variable that we can re-use to build the finalizers?

I did not find this prefix. Should we define it somewhere? as a repo-level constant, or just in `controller` package or defining finalizers ?

2022-08-11 08:11 UTC, pmalek commented on test/integration/controlplane_test.go
> +	err = controlplaneClient.Delete(ctx, controlplane.Name, metav1.DeleteOptions{})
~~Yes, in CI the cluster will be spawned just once and then destroyed but there might be cases where devs could run just a single test to verify functionality, bug fix, or something else and they'd like to reuse a cluster.~~

Ok, it seems that we already have a cleaner call in line 159: `cleaner.Add(controlplane)` which should cover what I described

2022-08-11 08:21 UTC, mlavacca commented on controllers/controlplane_controller_consts.go
> +	ControlPlaneFinalizerClusterResourcesGC ControlPlaneFinalizer = "gateway-operator.konghq.com/cluster-resource-gc"
We already have a file in which to store all consts, under `internal/consts/consts.go`. I think that place could be a good place to put this finalizer, instead of creating this new file.

2022-08-11 09:45 UTC, randmonkey commented on controllers/controlplane_controller_reconciler_utils.go
> +		}
updated.

2022-08-11 09:46 UTC, randmonkey commented on controllers/controlplane_controller_consts.go
> +	ControlPlaneFinalizerClusterResourcesGC ControlPlaneFinalizer = "gateway-operator.konghq.com/cluster-resource-gc"
> Instead of using a single Omni-comprehensive finalizer, I rather think that using a finalizer for each resource type (e.g., `gateway-operator.konghq.com/cleanup-clusterrole`, `gateway-operator.konghq.com/cleanup-clusterrolebinding`) is more meaningful for what resources are still to be collected and which are left in the cluster. WDYT?

used two finalizers for cleaning up each kind of resource, and moved the removing function to separate functions.

2022-08-11 09:49 UTC, randmonkey commented on controllers/controlplane_controller_consts.go
> +	ControlPlaneFinalizerClusterResourcesGC ControlPlaneFinalizer = "gateway-operator.konghq.com/cluster-resource-gc"
> We already have a file in which to store all consts, under `internal/consts/consts.go`. I think that place could be a good place to put this finalizer, instead of creating this new file.

IMHO, constants in `internal/consts/consts.go` are expected to be used in multiple packages or in different controllers, not a place to put ALL constants used in this repo. These finalizers are used only in controlplane controller, so I made a file to store them.

2022-08-11 09:51 UTC, randmonkey commented on controllers/controlplane_controller_consts.go
> +type ControlPlaneFinalizer string
This is used for enumerate possible finalizers added by controplane controller. added comments here.

2022-08-11 10:09 UTC, pmalek reviewed
Overall 👍 Left some nitpicks

2022-08-11 10:09 UTC, pmalek commented on controllers/controlplane_controller.go
> +		return ctrl.Result{}, err
nitpick: 

```suggestion
		return ctrl.Result{}, r.Client.Update(ctx, controlplane)
```

2022-08-11 10:09 UTC, pmalek commented on controllers/controlplane_controller.go
> +	}
👍

2022-08-11 10:09 UTC, pmalek commented on internal/utils/kubernetes/metadata.go
> +// retruns true if the ObjectMeta is really changed.
```suggestion
// If it exists, removes the finalizer from the slice.
// Returns true if the ObjectMeta has been changed.
```

2022-08-11 10:09 UTC, pmalek commented on internal/utils/kubernetes/metadata.go
> +// returns true if the ObjectMeta is really changed.
```suggestion
// If the finalizer does not exist, appends it to finalizers.
// Returns true if the ObjectMeta has been changed.
```

2022-08-11 10:15 UTC, randmonkey commented on controllers/controlplane_controller.go
> +		return ctrl.Result{}, err
fixed.

2022-08-11 10:15 UTC, randmonkey commented on internal/utils/kubernetes/metadata.go
> +// retruns true if the ObjectMeta is really changed.
updated.

2022-08-11 10:16 UTC, randmonkey commented on internal/utils/kubernetes/metadata.go
> +// returns true if the ObjectMeta is really changed.
updated.

2022-08-11 10:48 UTC, pmalek approved these changes
Ideally others would also chip in but this LGTM as of now.

2022-08-11 10:48 UTC, pmalek commented on controllers/controlplane_controller_consts.go
> +// ControlPlaneFinalizer are possible finalizers added by controlplane controller.
nit: (although I'm not sure this fits 100%)

```suggestion
// ControlPlaneFinalizer defines finalizers added by controlplane controller.
```

2022-08-11 12:42 UTC, mlavacca commented on controllers/controlplane_controller_consts.go
> +	ControlPlaneFinalizerCleanupClusterRole ControlPlaneFinalizer = "gateway-operator.konghq.com/cleanup-clusterrole"
I personally keep advocating for moving these constants under internal/consts/consts.go. We have the labels to retrieve the objects stored in that file, along with k8s name prefixes and so on. TBH, I think that scattering around constants that are functionally correlated (all of them are meant to enrich K8s objects with additional info) will lead to a code quality decrease.

2022-08-11 12:42 UTC, mlavacca commented on controllers/controlplane_controller_consts.go
> +	ControlPlaneFinalizerCleanupClusterRole ControlPlaneFinalizer = "gateway-operator.konghq.com/cleanup-clusterrole"
Other than this aspect, this lgtm

2022-08-11 14:55 UTC, shaneutt reviewed
No blockers, but a couple comments for your considerations.

2022-08-11 14:55 UTC, shaneutt commented on controllers/controlplane_controller.go
> +		return ctrl.Result{}, err.ErrorOrNil()
Reading this block it's not clear where the finalizers are actually being removed at a glance. You have to dig in to the binding and role removal methods to find out that's where's it's being done. For future code readers it would be better to have upfront clarity on the finalizer handling. Another side effect of how this is currently done is that under some (albeit minor) situations you could end up with the object in the queue multiple times.

Here's an alternative implementation for your considerations:

```go
if !controlplane.DeletionTimestamp.IsZero() {
	// wait for termination grace period before cleaning up roles and bindings
	if controlplane.DeletionTimestamp.After(metav1.Now()) {
		debug(log, "control plane deletion still under grace period", controlplane)
		return ctrl.Result{RequeueAfter: constants.GracePeriodRequeueDelay}
	}

	// ensure that the rolebindings which were created for the ControlPlane are deleted
	if err := r.ensureOwnedClusterRoleBindingsDeleted(ctx, controlplane); err != nil {
		return ctrl.Result{}, err
	}

	// now that RoleBindings are cleaned up, remove the relevant finalizer
	if k8sutils.RemoveFinalizerInMetadata(&controlplane.ObjectMeta, string(ControlPlaneFinalizerCleanupClusterRoleBinding)) {
		return ctrl.Result{}, r.Client.Update(ctx, controlplane) // requeue here until rolebinding finalizer is removed 
	}

	// ensure that the roles created for the controlplane are deleted
	if err := r.ensureOwnedClusterRolesDeleted(ctx, controlplane); err != nil {
		return ctrl.Result{}, err
	}

	// now that Roles are cleaned up, remove the relevant finalizer
	if k8sutils.RemoveFinalizerInMetadata(&controlplane.ObjectMeta, string(ControlPlaneFinalizerCleanupClusterRole)) {
		return ctrl.Result{}, r.Client.Update(ctx, controlplane) // requeue here until role finalizer is removed
	}

	return ctrl.Result{}, nil // cleanup completed
}
```

So with the above example we would end up with more clarity up front on how finalizers are being handled: the code reader can see that we're very intentionally deleting sub-resources and then removing the relevant finalizer at a glance. Also with the above we're expressing the re-entrant code in a way that more clearly defines re-queues as happening immediately after the object is updated which in general can be beneficial for code clarity, reducing problems like extra enqueuing of the same object, and otherwise make the logic more predictable.

All that said, these things are very minor and so I don't consider this comment a blocker. I would just ask that you consider these points and see if there's ways we can improve on readability and re-entry.

2022-08-11 14:55 UTC, shaneutt commented on controllers/controlplane_controller.go
> +	if metaChanged {
nit: `metaChanged` is a very general way to describe what the results of the `EnsureFinalizerInMetadata` function does, what do you think about this alternative name?

```suggestion
	finalizersChanged := k8sutils.EnsureFinalizerInMetadata(&controlplane.ObjectMeta, string(ControlPlaneFinalizerCleanupClusterRole))
	finalizersChanged = finalizersChanged || k8sutils.EnsureFinalizerInMetadata(&controlplane.ObjectMeta, string(ControlPlaneFinalizerCleanupClusterRoleBinding))
	if finalizersChanged {
```

2022-08-11 16:23 UTC, randmonkey commented on controllers/controlplane_controller.go
> +	if !controlplane.DeletionTimestamp.IsZero() {
Correct me if I made any mistakes: the deletion timestamp could NOT be unset or set to a later, so we could requeue the controlplane when the grace period expires. If the deletion timestamp is changed, the update would trigger another round of reconclilation.

2022-08-11 16:25 UTC, randmonkey commented on controllers/controlplane_controller.go
> +		return ctrl.Result{}, err.ErrorOrNil()
```go
if controlplane.DeletionTimestamp.After(metav1.Now()) {
		debug(log, "control plane deletion still under grace period", controlplane)
		return ctrl.Result{RequeueAfter: constants.GracePeriodRequeueDelay}
	}
```
Correct me if I made any mistakes: the deletion timestamp could NOT be unset or set to a later, so we could requeue the controlplane when the grace period expires (as in the following snippet) If the deletion timestamp is changed, the update would trigger another round of reconclilation.

```go
		if controlplane.DeletionTimestamp.After(metav1.Now().Time) {
			debug(log, "control plane deletion still under grace period", controlplane)
			return ctrl.Result{
				Requeue: true,
				// Requeue when grace period expires.
				// If deletion timestamp is changed,
				// the update will trigger another round reconilation.
				// so we do not consider updates of deletion timestmp here.
				RequeueAfter: time.Until(controlplane.DeletionTimestamp.Time),
			}, nil
		}
```

2022-08-11 16:26 UTC, randmonkey commented on controllers/controlplane_controller.go
> +	if metaChanged {
fixed.

2022-08-11 16:34 UTC, randmonkey commented on controllers/controlplane_controller.go
> +		return ctrl.Result{}, err.ErrorOrNil()
taken this implementation.

2022-08-11 16:37 UTC, randmonkey commented on controllers/controlplane_controller_consts.go
> +	ControlPlaneFinalizerCleanupClusterRole ControlPlaneFinalizer = "gateway-operator.konghq.com/cleanup-clusterrole"
I put these constants in separate file because I took the similar usage of `*_conditions.go`. These are only used in one controller, so they are not put in the common `consts` package. The finalizers are also only used in one controller, I think I need a reason to treat them in different way with the conditions of each resource.

2022-08-11 16:41 UTC, randmonkey commented on controllers/controlplane_controller_consts.go
> +// ControlPlaneFinalizer are possible finalizers added by controlplane controller.
updated.

2022-08-11 17:23 UTC, mlavacca commented on controllers/controlplane_controller_consts.go
> +	ControlPlaneFinalizerCleanupClusterRole ControlPlaneFinalizer = "gateway-operator.konghq.com/cleanup-clusterrole"
well, I actually never said that we should have a large constant pool for ALL the constants of the projects, I was referring only to the ones used to enrich K8s objects, as labels, annotations, or finalizers. Btw, I guess it is fine as it is.

2022-08-11 18:08 UTC, shaneutt commented on controllers/controlplane_controller.go
> +		return ctrl.Result{}, err.ErrorOrNil()
Yes this is a good way to do it, I like it :+1:

2022-08-11 18:13 UTC, shaneutt submitted a review, later dismissed
couple more super tiny comments, but then looks really good!

2022-08-11 18:13 UTC, shaneutt commented on controllers/controlplane_controller.go
> +				// so we do not consider updates of deletion timestmp here.
```suggestion
				// so we do not consider updates of deletion timestamp here.
```

2022-08-11 18:13 UTC, shaneutt commented on controllers/controlplane_controller.go
> +		debug(log, "remove owned cluster wide resources", controlplane)
```suggestion
		debug(log, "removing owned roles and role bindings", controlplane)
```

2022-08-12 03:04 UTC, randmonkey commented on controllers/controlplane_controller.go
> +				// so we do not consider updates of deletion timestmp here.
fixed typos here.

2022-08-12 03:05 UTC, randmonkey commented on controllers/controlplane_controller.go
> +		debug(log, "remove owned cluster wide resources", controlplane)
updated.

2022-08-12 07:27 UTC, pmalek commented on internal/utils/kubernetes/metadata.go
> +func RemoveFinalizerInMetadata(metadata *metav1.ObjectMeta, finalizer string) bool {
If the newly introduced type is to have a purpose, it should be accepted in here (the same above in `EnsureFinalizerInMetadata`

```suggestion
// RemoveFinalizerInMetadata removes the finalizer from the finalizers in ObjectMeta.
// If it exists, remove the finalizer from the slice.
// Returns true if the ObjectMeta has been changed.
func RemoveFinalizerInMetadata(metadata *metav1.ObjectMeta, finalizer ControlPlaneFinalizer) bool {
```

WDYT @randmonkey ?

2022-08-12 08:12 UTC, randmonkey commented on internal/utils/kubernetes/metadata.go
> +func RemoveFinalizerInMetadata(metadata *metav1.ObjectMeta, finalizer string) bool {
The purpose of `RemoveFinalizerInMetadata` is a general function for adding or removing finalizers, not limited to `ControlPlane`. So here I did not use `ControlPlaneFinalizer` here.

2022-08-12 08:19 UTC, pmalek commented on internal/utils/kubernetes/metadata.go
> +func RemoveFinalizerInMetadata(metadata *metav1.ObjectMeta, finalizer string) bool {
So perhaps the type shouldn't be so narrow i.e. defined only for controlplane finalizers but generally for finalizers?

This way the funcs you've added (e.g. the one above) could use it and also in the future if there's new finalizers added for other type like e.g. `DataPlane` then it can be reused.

WDYT @randmonkey ?

2022-08-12 08:50 UTC, randmonkey commented on internal/utils/kubernetes/metadata.go
> +func RemoveFinalizerInMetadata(metadata *metav1.ObjectMeta, finalizer string) bool {
I defined the type `ControlPlaneFinalizer` just to annotate that these are finalizers added to `ControlPlane`s by controlplane controller, but not define a type for all finalizers. If you really, really, really ... concern about the type being defined but not used, I think I could remove the definition of `ControlPlaneFinalizer`, and use string directly when call these functions in controlplane controller.

2022-08-12 12:34 UTC, pmalek commented on internal/utils/kubernetes/metadata.go
> +func RemoveFinalizerInMetadata(metadata *metav1.ObjectMeta, finalizer string) bool {
Feel free to resolve this comment if you disagree with this approach.

I'll let others express their view on this.

2022-08-12 14:20 UTC, shaneutt submitted a review, later dismissed

2022-08-13 12:54 UTC, shaneutt commented
Looks like there's a couple small lint issues that need to be fixed before we can proceed.

2022-08-15 06:13 UTC, randmonkey commented
> Looks like there's a couple small lint issues that need to be fixed before we can proceed.

fixed. lint issues comes out since lint is enabled on test files in some recent PRs.

2022-08-15 19:59 UTC, shaneutt approved these changes

2022-08-15 19:59 UTC, merged