feat: keep Deployment environments updated
Kong/gateway-operator pull request #218
Opened 2022-08-23 20:25 UTC by rainest

**What this PR does / why we need it**:
Update the Deployment associated with a ControlPlane or DataPlane if its current actual EnvVar set differs from the set generated by the reconciler. #97 doesn't strictly need the DataPlane to do this, but the two should be consistent and we [want this UX anyway](https://github.com/Kong/gateway-operator/issues/97#issuecomment-1224155582).

Add Service information to DataPlane status.

Have the ControlPlane reconciler watch for changes to the controlled DataPlane. If the DataPlane status contains a new Service, the generated EnvVars will differ and the reconciler will update the ControlPlane with the new publish service.

**Which issue this PR fixes**
Fix #97 

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] ~the `CHANGELOG.md` release notes have been updated to reflect significant changes~ alphazone

2022-08-23 20:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/gateway-operator?pullRequest=218) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/gateway-operator?pullRequest=218) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/gateway-operator?pullRequest=218) it.</sub>

2022-08-23 20:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/gateway-operator?pullRequest=218) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/gateway-operator?pullRequest=218) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/gateway-operator?pullRequest=218) it.</sub>

2022-08-23 21:07 UTC, shaneutt commented on apis/v1alpha1/dataplane_types.go
> +	Service string `json:"service,omitempty"`
I'm not necessarily opposed to this, but I would like to talk through this some.

One of the implications of adding this `Service` reference would seem to be that the `DataPlane` has some kind of "ownership" over the `Service`, which it does not: ownership is maintained by the `Gateway`. In the current state where the `Gateway` owns the `Service`, does this field have any meaning in the context of directly using the `DataPlane` API?

What I'm starting to realize is that the `Service` should actually belong to the `DataPlane`, especially if we add a reference like this. Are you opposed to moving the `Service` logic from the `Gateway` controller to the `DataPlane` controller so that this works when a caller directly uses the `DataPlane` API? Can you see any downsides of doing so?

2022-08-23 21:31 UTC, rainest commented on apis/v1alpha1/dataplane_types.go
> +	Service string `json:"service,omitempty"`
Wait, what? I don't follow, that doesn't seem to align with the current code. The DataPlane controller does [create its Service](https://github.com/Kong/gateway-operator/blob/758facd52c2e5eb1f5b1a4f37be621376f422eb6/controllers/dataplane_controller.go#L79-L80), and the standalone DataPlane test [checks for its existence](https://github.com/Kong/gateway-operator/blob/758facd52c2e5eb1f5b1a4f37be621376f422eb6/test/integration/dataplane_test.go#L69-L71).

The Gateway controller's interaction with it is just to retrieve the Service associated with a DataPlane and then provide it to the ControlPlane builder and its own status setter.

2022-08-23 22:17 UTC, shaneutt commented on apis/v1alpha1/dataplane_types.go
> +	Service string `json:"service,omitempty"`
Whoops! :facepalm: my bad sorry.

2022-08-24 03:34 UTC, randmonkey requested changes

2022-08-24 03:34 UTC, randmonkey commented on controllers/controlplane_controller.go
> +	var dataplaneServiceName string
where is this variable `dataplaneServiceName` used except for the following `else` block? If nowhere else used, the variable should not be defined in the block.

2022-08-24 03:34 UTC, randmonkey commented on controllers/controlplane_controller_reconciler_utils.go
> +			existingDeployment.Spec.Template.Spec.Containers[0].Env = controlplane.Spec.Env
We need also check `EnvFrom` here.

2022-08-24 03:34 UTC, randmonkey commented on controllers/dataplane_controller_reconciler_utils.go
> +		if !reflect.DeepEqual(existingDeployment.Spec.Template.Spec.Containers[0].Env, dataplane.Spec.Env) {
We need also check `EnvFrom` here.

2022-08-24 03:34 UTC, randmonkey commented on controllers/utils.go
> +func setCALogger(logger logr.Logger) {
Seems that we need to add such functions and package level `sync.Once` variables for each place where we want to add some fields inside functions, in order to avoid data race? IHAC that there would be too many such things. But for now, I think it is acceptable before we have got a better solution to loggings.

2022-08-24 11:27 UTC, pmalek commented on controllers/dataplane_controller_reconciler_utils.go
> +		if !reflect.DeepEqual(existingDeployment.Spec.Template.Spec.Containers[0].Env, dataplane.Spec.Env) {
BTW I do understand that we have just 1 container (kong gateway) in data plane pod but I'd be careful with things like `.Spec.Template.Spec.Containers[0]`.

Why not be on the safe side and do the traversal over the containers slice and pick the one with the gateway? My main point is that no one will remember to make this change when at some point we introduce e.g. a sidecar for whatever purposes.

2022-08-24 20:04 UTC, rainest commented on controllers/dataplane_controller_reconciler_utils.go
> +		if !reflect.DeepEqual(existingDeployment.Spec.Template.Spec.Containers[0].Env, dataplane.Spec.Env) {
Is there a convenience function for this already? I can write one but it seems like getting a container by name is something client-go would provided, I just don't know what it is if so.

2022-08-24 20:13 UTC, rainest commented on controllers/utils.go
> +func setCALogger(logger logr.Logger) {
This is a special case where cfssl wants to handle its own logging instead of returning errors, so we have to stuff our own logger in. Ideally it wouldn't do that, but it's not so annoying that I'd rather write our own CA tool.

The typical case where we just call `logger := log.FromContext(ctx).WithName("MTLSCertificateCreation")` or whatever and use that doesn't need this because we're the ones handling the logs, and we use function-scoped instead of package-scoped loggers. Most libraries we use return errors that we then log, instead of using their own logging. deck is the other main exception, but that's our own damn fault.

2022-08-25 06:51 UTC, randmonkey commented on controllers/controlplane_controller_reconciler_utils.go
> +	rutils "github.com/kong/gateway-operator/internal/utils/kubernetes/resources"
There is no need to import `github.com/kong/gateway-operator/internal/utils/kubernetes/resources` as `rutils` again, it is already imported. (linter did not check this?)

2022-08-25 06:51 UTC, randmonkey commented on controllers/controlplane_controller_reconciler_utils.go
> +		container := rutils.GetPodContainerByName(&existingDeployment.Spec.Template.Spec, consts.ControlPlaneControllerContainerName)
IMO it is better to return `true` and update deployment here. If we return an error here, the reconciling will get a constant failure if the deployment is modified that it did not have such a container.

2022-08-25 06:51 UTC, randmonkey commented on controllers/dataplane_controller.go
> +		return ctrl.Result{}, err // requeue will be triggered by the creation or update of the owned object
Is `return ctrl.Result{}, r.ensureDataPlaneServiceStatus(ctx, dataplane, dataplaneService.Name)` better?

2022-08-25 06:51 UTC, randmonkey commented on test/integration/controlplane_test.go
> +	rutils "github.com/kong/gateway-operator/internal/utils/kubernetes/resources"
for consistency, Is it OK to import `github.com/kong/gateway-operator/internal/utils/kubernetes/resources` as `k8sresources` here?

2022-08-25 06:51 UTC, randmonkey commented on test/integration/gateway_test.go
> +	rutils "github.com/kong/gateway-operator/internal/utils/kubernetes/resources"
ditto here.

2022-08-25 06:51 UTC, randmonkey commented on controllers/dataplane_controller_reconciler_utils.go
> +	rutils "github.com/kong/gateway-operator/internal/utils/kubernetes/resources"
For consistency, I think it is better to import as `k8sresources` here,

2022-08-25 18:19 UTC, rainest commented on controllers/controlplane_controller_reconciler_utils.go
> +	rutils "github.com/kong/gateway-operator/internal/utils/kubernetes/resources"
Yeah, I missed the existing import/rename convention, thanks.

2022-08-25 18:27 UTC, rainest commented on controllers/controlplane_controller_reconciler_utils.go
> +		container := rutils.GetPodContainerByName(&existingDeployment.Spec.Template.Spec, consts.ControlPlaneControllerContainerName)
Is there a reason to actually return here? I think we'd only want that if there was some reason we couldn't proceed with the other checks/updates after.

I think we want what https://github.com/Kong/gateway-operator/pull/218/commits/6d40d578e99a6329f6d913af4d1bf10780ab872c adds, where it's just the same as the other things that set `updated=true`. We have to rely on the generated containers always having that container, but if it doesn't we've either done something wrong or so weird that we need to refactor this section anyway.

We could kinda skip that requirement if we update immediately here and return, but not really since if we're generating Deployments without that container it'll just get stuck in a loop running that update repeatedly

2022-08-26 03:21 UTC, randmonkey approved these changes

2022-08-26 03:21 UTC, merged