only one gateway status update per reconciliation loop
Kong/gateway-operator pull request #226
Opened 2022-08-24 12:09 UTC by mlavacca

**What this PR does / why we need it**:

**Which issue this PR fixes**
#203 

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect significant changes

2022-08-25 08:38 UTC, randmonkey commented on controllers/controlplane_controller.go
> +			return ctrl.Result{}, r.Client.Patch(ctx, newControlplane, client.MergeFrom(controlplane)) // Controlplane update will requeue
Is there any benefit to use `Patch` instead of `Update`? To avoid conflicts?

2022-08-25 09:08 UTC, mlavacca commented on controllers/controlplane_controller.go
> +			return ctrl.Result{}, r.Client.Patch(ctx, newControlplane, client.MergeFrom(controlplane)) // Controlplane update will requeue
Yes, conflicts shouldn't happen with Patch. Furthermore, it is idempotent (applying twice the same patch, the `resourceVersion` isn't touched).

2022-08-26 03:47 UTC, randmonkey reviewed
Generally good, but some minor comments remains.

2022-08-26 03:47 UTC, randmonkey commented on controllers/gateway_controller_reconciler_utils.go
> +func (r *GatewayReconciler) ensureGatewayConnectivityStatus(ctx context.Context, gateway *gatewayDecorator, dataplane *operatorv1alpha1.DataPlane) (message string) {
Why do we want to change the function signature to return `string` here? I know the purpose here is to directly use the returned value as message in the condition, but IMO it is better to return an error here to annotate that something incorrect happened.

2022-08-26 08:22 UTC, mlavacca commented on controllers/gateway_controller_reconciler_utils.go
> +func (r *GatewayReconciler) ensureGatewayConnectivityStatus(ctx context.Context, gateway *gatewayDecorator, dataplane *operatorv1alpha1.DataPlane) (message string) {
No specific reason. Since we'd use that error as a string, why not return a string? Just a matter of readability, but I can change the signature and return an error if you deem it :)

2022-08-26 12:02 UTC, shaneutt requested changes
Looks great, a very thoughtful patch :+1: 

My comments are all minor, my only side notes are these:

- we should verify that we've performed manual testing before merging this PR
- if feasible we should extend our E2E tests: creating 5+ `Gateway` resources should result in no 409's in the pod logs
- we should look for any opportunity to extend our current tests, if I'm not mistaken we've added a condition where there's a connectivity error for the `Gateway`, correct? Can we have tests that verify this state?

2022-08-26 14:23 UTC, mlavacca commented
> we should verify that we've performed manual testing before merging this PR

I performed manual testing by deploying up to 10 Gateways at the same time and no error occurred. But I found out something curious: with that number of gateways deployed in parallel, the time needed by the Gateways to get ready rose above 3 minutes. I think this happens because there is a lack of resources in the cluster, but the deployments don't have requests set. The reconciliation is very fast, but the dataplane pods take a lot to get ready, and sometimes it can happen that they don't reply to the controlplane resulting in the controlplane crash. I think we can solve this issue by setting resource requests (and we should also set limits) in both controlplanes and dataplanes.

2022-08-26 15:51 UTC, pmalek commented on controllers/gateway_controller_reconciler_utils.go
> +			return errors.New("missing loadbalancer.ingress[0].ip")
Small nit: maybe add service name to the error message?

2022-08-26 15:51 UTC, pmalek commented on controllers/gateway_controller_reconciler_utils.go
> +	for _, ip := range append(gatewayIPs, svc.Spec.ClusterIP) {
Hmm 🤔 this range param seems a little unconventional. Can we just `append` to `gatewayIPs` in a separate line? Wouldn't that bit a bit more readable? WDYT?

2022-08-26 16:51 UTC, shaneutt commented
> > we should verify that we've performed manual testing before merging this PR
> 
> I performed manual testing by deploying up to 10 Gateways at the same time and no error occurred. But I found out something curious: with that number of gateways deployed in parallel, the time needed by the Gateways to get ready rose above 3 minutes. I think this happens because there is a lack of resources in the cluster, but the deployments don't have requests set. The reconciliation is very fast, but the dataplane pods take a lot to get ready, and sometimes it can happen that they don't reply to the controlplane resulting in the controlplane crash. I think we can solve this issue by setting resource requests (and we should also set limits) in both controlplanes and dataplanes.
> 
> EDIT: I created an issue for that in #240

Sounds good, albeit there was an issue open which already was asking for memory and cpu limits, I commented on #240 about it.

> > if feasible we should extend our E2E tests: creating 5+ Gateway resources should result in no 409's in the pod logs
> 
> Considering that I replaced all the gateway status updates with patches, do you think this is something we should check in any case? I mean, theoretically, no conflict can happen with patches

We've changed the behavior of reconciliation in a relatively significant way. The main goal I have with this comment is that we should try and capture the intent of how things should be working in tests such that if someone made a PR that went against that prior intent (e.g. introduced a regression) we would get test feedback about this rather than silently allowing it through.

> > we should look for any opportunity to extend our current tests, if I'm not mistaken we've added a condition where there's a connectivity error for the Gateway, correct? Can we have tests that verify this state?
> 
> That status already existed, I changed only the way its update is performed. Since this is a status related to a transitory state, I see hard to test the existence of that status in the integration tests because it implies that either the cluster is not working properly (addresses are not assigned), or the operator is not working properly (the service hasn't been created). I think we should test this kind of stuff in the controller's unit tests.

Adding unit tests is always a good idea. As far as something more on the integration side of things I get that creating "broken" setups can be very challenging and time consuming, and you do have to balance that against the value you're adding. Use your best judgement here.

2022-08-30 11:27 UTC, shaneutt approved these changes

2022-08-30 11:29 UTC, shaneutt approved these changes
I think we should try and add some unit test coverage as previously discussed, then lgtm.

2022-08-30 12:27 UTC, mlavacca commented
> I think we should try and add some unit test coverage as previously discussed, then lgtm.

I'm working on adding a new e2e test that checks the operator logs. Do you prefer it to be added by a subsequent PR or do we wait for it before merging this one?

2022-08-30 12:28 UTC, shaneutt commented
> > I think we should try and add some unit test coverage as previously discussed, then lgtm.
> 
> I'm working on adding a new e2e test that checks the operator logs. Do you prefer it to be added by a subsequent PR or do we wait for it before merging this one?

If you're actively working on it, then ideally let's wait and get it in here.

2022-08-30 12:39 UTC, mlavacca commented
> > > I think we should try and add some unit test coverage as previously discussed, then lgtm.
> > 
> > 
> > I'm working on adding a new e2e test that checks the operator logs. Do you prefer it to be added by a subsequent PR or do we wait for it before merging this one?
> 
> If you're actively working on it, then ideally let's wait and get it in here.

I just realized it'd be way easier to merge this change before the e2e test because in the e2e tests we deploy the operator from main, and without having this change merged it's tricky to properly test it. I'll merge this one and open a new PR with the e2e test.

2022-08-30 12:47 UTC, merged