docs - Kong enterprise in DBLess mode
Kong/gateway-operator pull request #237
Opened 2022-08-26 10:33 UTC by mlavacca

**What this PR does / why we need it**:

**Which issue this PR fixes**
Fixes #165 

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect significant changes

2022-08-26 16:40 UTC, shaneutt requested changes
Mostly LGTM. However we should add to this documentation some kind of litmus test: a one-liner that checks vitals or some other enterprise specific functionality to simply verify that enterprise mode was enabled properly (and we should make sure we're testing that ourselves).

2022-08-29 09:28 UTC, pmalek commented on README.md
> +---
nit: I find the quote blocks with NOTEs to be more distinguishable while going through a block of text. Apart from that I think that this type of usage of block separation is a little bit incorrect.

```suggestion

> **Note**: the license secret, the `GatewayConfiguration`, and the `Gateway` MUST be created in the same namespace.

```

2022-08-29 09:28 UTC, pmalek commented on README.md
> +Create a secret with the Kong license in the namespace that you intend to use for deploying the gateway.
How about putting those steps in a bullet list? Wouldn't that be easier to follow by users?

2022-08-29 12:19 UTC, mlavacca commented on README.md
> +Create a secret with the Kong license in the namespace that you intend to use for deploying the gateway.
I thought the same but didn't find any way to add code sections in a bullet list without messing up the list. Any advice?

2022-08-29 14:24 UTC, shaneutt submitted a review, later dismissed

2022-08-29 15:29 UTC, mlavacca commented on README.md
> +Create a secret with the Kong license in the namespace that you intend to use for deploying the gateway.
@pmalek ping so that we can merge it :)

2022-08-30 08:45 UTC, pmalek commented on README.md
> +Create a secret with the Kong license in the namespace that you intend to use for deploying the gateway.
Omg I didn't leave a comment?! I'm almost certain I had a comment lined up for this. 

Anyway, you can indent the whole code snippet to make it indented at the same level as the bullet points.

2022-08-30 10:48 UTC, mlavacca commented on README.md
> +Create a secret with the Kong license in the namespace that you intend to use for deploying the gateway.
Fixed, PTAL

2022-08-30 11:23 UTC, shaneutt approved these changes

2022-08-30 12:00 UTC, pmalek commented on README.md
> +2. Create a `GatewayConfiguration` specifying the enterprise container image and the environment variable referencing the license secret. The operator will use the image and the environment variable
nit: if you use `1.` for every point in a numbered list in markdown it will do the numbering automatically for you. This way you can save yourself some time in the future and avoid renumbering the list if you end up adding a point in the middle of the list.

2022-08-30 12:00 UTC, pmalek approved these changes

2022-08-30 12:24 UTC, mlavacca commented on README.md
> +2. Create a `GatewayConfiguration` specifying the enterprise container image and the environment variable referencing the license secret. The operator will use the image and the environment variable
nice, didn't know that!

2022-08-30 12:54 UTC, merged