logging e2e test
Kong/gateway-operator pull request #269
Opened 2022-08-31 15:17 UTC by mlavacca

**What this PR does / why we need it**:
Addition of a e2e test that:
1. creates 5 gateways sequentially
2. wait for all the gateways to be ready
3. creates all the 5 gateways sequentially
4. wait for all the sub-resources are correctly deleted
5. check the gateway operator error message: no error must occur (apart those set in the map of the allowed error messages)

**Which issue this PR fixes**

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [x] the `CHANGELOG.md` release notes have been updated to reflect significant changes

2022-08-31 17:23 UTC, shaneutt requested changes

2022-08-31 17:23 UTC, shaneutt commented on Makefile
> +	GOFLAGS="-tags=logs_e2e_tests" go test -race -v ./test/e2e/...
It's not clear to me why this E2E test has become an entirely separate thing, is this because our E2E testing suite currently provides a "default" cluster where in this case we want our own? Because I think that's a problem we've been needing to solve with the E2E test suite in general, and I would hate to start down this path of adding more build tags and more separation when what we really want is for each E2E test to just build and manage its own cluster :thinking:

2022-08-31 17:51 UTC, mlavacca commented on Makefile
> +	GOFLAGS="-tags=logs_e2e_tests" go test -race -v ./test/e2e/...
yes, the issue here is that we need a fresh cluster with a fresh operator to run this test. We need this because we read all the operator logs and check that no error occurs. In a dirty env in which other tests have already run (such as the webhook test), we end up checking also the log lines produced by those tests and eventually make the test fail because of errors triggered by other tests (maybe on purpose). I don't like this approach either, but it's the only one I found that fits our e2e env.

2022-08-31 18:46 UTC, shaneutt commented on Makefile
> +	GOFLAGS="-tags=logs_e2e_tests" go test -race -v ./test/e2e/...
How do you feel about taking this time to rework the E2E environment so that it matches a bit closer to KIC? e.g. drop the current cluster setup and instead make each test responsible for it's own cluster and/OR combining tests which are compatible?

2022-09-01 10:15 UTC, mlavacca commented on Makefile
> +	GOFLAGS="-tags=logs_e2e_tests" go test -race -v ./test/e2e/...
Sure, I created an issue for this: https://github.com/Kong/gateway-operator/issues/279

2022-09-01 18:37 UTC, shaneutt requested changes
Mostly looks good, just a couple minor comments.

2022-09-01 18:37 UTC, shaneutt commented on test/e2e/operatorLogs_test.go
> +	// the total number of gateways that are created and deleted one after the other
```suggestion
	// parallelGateways is the total number of gateways that are created and deleted one after the other
```

2022-09-01 18:37 UTC, shaneutt commented on test/e2e/operatorLogs_test.go
> +	gatewayReadyTimeLimit = time.Minute * 3
We have this concept in the integration test suite as well, don't we? I wouldn't be opposed to starting to collect these things (especially the ones that can be shared between the integration and e2e test suites, because they should be the same) somewhere like `internal/utils/test/` or something like that :thinking:

2022-09-01 18:37 UTC, shaneutt commented on test/e2e/operatorLogs_test.go
> +	// get the gateway operator pod
```suggestion
	t.Log("finding the Pod for the Gateway Operator")
```

2022-09-01 18:37 UTC, shaneutt commented on test/e2e/operatorLogs_test.go
> +// integration and e2e tests
This fits in with a comment I made above, let's just put this stuff in `internal/utils/test/` wdyt?

2022-09-02 08:26 UTC, mlavacca commented on test/e2e/operatorLogs_test.go
> +// integration and e2e tests
Sure, I'll do this refactoring

2022-09-02 17:16 UTC, shaneutt commented on test/e2e/operatorLogs_test.go
> +// integration and e2e tests
Have we completed consolidating the helpers? Would seem we should remove this comment if so?

2022-09-05 08:19 UTC, mlavacca commented on test/e2e/operatorLogs_test.go
> +// integration and e2e tests
Yep, I rebased the PR quickly and overlooked removing this comment and the comment below. It should be fine now.

2022-09-06 14:02 UTC, shaneutt approved these changes

2022-09-06 14:10 UTC, merged