[WIP] feat: update sub-resources
Kong/gateway-operator pull request #294
Opened 2022-09-02 12:10 UTC by randmonkey

**What this PR does / why we need it**:

**Which issue this PR fixes**

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect significant changes

2022-09-05 07:36 UTC, mlavacca requested changes

2022-09-05 07:36 UTC, mlavacca commented on controllers/controlplane_controller_reconciler_utils.go
> +		if r.deploymentSpecVolumesNeedsUpdate(&generatedDeployment.Spec, &existingDeployment.Spec) {
We should also check the `ServiceAccount` to be used by the controlplane

2022-09-05 07:36 UTC, mlavacca commented on internal/utils/kubernetes/resources/volumes.go
> +func GetPodVolumeByName(podSpec *corev1.PodSpec, name string) *corev1.Volume {
The `internal/utils/kubernetes/resources` package should contain only the generators for each kind of resource. So I see this helper as a getter that can be put under `internal/utils/kubernetes/<something>`. This also applies to `GetPodContainerByName` that I overlooked before. WDYT?

2022-09-05 07:36 UTC, mlavacca commented on controllers/gateway_controller.go
> +	debug(log, "ensuring controlplane config is up to date", gateway)
A PR that refactors logging has been recently merged on main. These kinds of logs that "state" what's going to happen as the next operation should be set as `trace` instead of `debug`.

2022-09-05 07:36 UTC, mlavacca commented on controllers/gateway_controller.go
> +		err = r.Client.Update(ctx, dataplane)
can we log with `debug` verbosity the outcome of this operation?

2022-09-05 07:36 UTC, mlavacca commented on controllers/gateway_controller.go
> +		err = r.Client.Update(ctx, controlplane)
can we log with debug verbosity the outcome of this operation?

2022-09-05 07:36 UTC, mlavacca commented on controllers/controlplane_controller_utils.go
> +func generateNewDeploymentForControlPlane(controlplane *operatorv1alpha1.ControlPlane, serviceAccountName,
What do you think about moving this deployment generator to the generators pkg `internal/utils/kubernetes/resources`?

2022-09-05 09:41 UTC, randmonkey commented on internal/utils/kubernetes/resources/volumes.go
> +func GetPodVolumeByName(podSpec *corev1.PodSpec, name string) *corev1.Volume {
Have we specified 
```
The internal/utils/kubernetes/resources package should contain only the generators for each kind of resource.
```
anywhere? If so, I think it would be good to put the functions to `nternal/utils/kubernetes/pod_utis.go` and call them by `k8sutil.GetPodVolumeByName`.

2022-09-05 09:55 UTC, mlavacca commented on internal/utils/kubernetes/resources/volumes.go
> +func GetPodVolumeByName(podSpec *corev1.PodSpec, name string) *corev1.Volume {
No, we didn't write any disclaimer like that. If you want to add, it'd be cool. Putting those helpers under `internal/utils/kubernetes/pod_utis.go` sounds good.

2022-09-05 10:25 UTC, randmonkey commented on controllers/controlplane_controller_utils.go
> +func generateNewDeploymentForControlPlane(controlplane *operatorv1alpha1.ControlPlane, serviceAccountName,
It is a good idea, but I do not want to include the change in this PR because this would be better to be done in another issue and PR to move the code for generating k8s resources.

2022-09-05 10:26 UTC, randmonkey commented on controllers/controlplane_controller_reconciler_utils.go
> +		if r.deploymentSpecVolumesNeedsUpdate(&generatedDeployment.Spec, &existingDeployment.Spec) {
done.

2022-09-05 10:26 UTC, randmonkey commented on controllers/gateway_controller.go
> +	debug(log, "ensuring controlplane config is up to date", gateway)
fixed.

2022-09-05 10:26 UTC, randmonkey commented on controllers/gateway_controller.go
> +		err = r.Client.Update(ctx, controlplane)
done

2022-09-05 10:26 UTC, randmonkey commented on controllers/gateway_controller.go
> +		err = r.Client.Update(ctx, dataplane)
done

2022-09-05 12:36 UTC, mlavacca requested changes

2022-09-05 12:36 UTC, mlavacca commented on internal/utils/kubernetes/resources/volumes.go
> +func GetPodVolumeByName(podSpec *corev1.PodSpec, name string) *corev1.Volume {
what about moving this to `internal/utils/kubernetes/pod_utis.go`?

2022-09-05 12:36 UTC, mlavacca commented on controllers/gateway_controller.go
> +		debug(log, "dataplane config is out of date, updating", gateway)
can we use trace level?

2022-09-05 12:36 UTC, mlavacca commented on controllers/gateway_controller.go
> +		err = r.Client.Update(ctx, dataplane)
I don't see any feedback about the outcome of the update operation 😕

2022-09-05 12:36 UTC, mlavacca commented on controllers/gateway_controller.go
> +		debug(log, "dataplane should be updated to expected state", dataplane)
This is the same line above, I'd say to keep only one related to this update.

2022-09-05 12:36 UTC, mlavacca commented on controllers/gateway_controller.go
> +		err = r.Client.Update(ctx, controlplane)
as above, I don't see a feedback. I'd expect something like 
```go
  debug(log, "controlplane successfully updated", controlplane)
```

before setting the condition with the reason `ResourceCreatedOrUpdatedReason `

2022-09-06 03:20 UTC, randmonkey commented on controllers/gateway_controller.go
> +		debug(log, "dataplane should be updated to expected state", dataplane)
fixed.

2022-09-06 03:20 UTC, randmonkey commented on controllers/gateway_controller.go
> +		debug(log, "dataplane config is out of date, updating", gateway)
updated.

2022-09-06 03:20 UTC, randmonkey commented on internal/utils/kubernetes/resources/volumes.go
> +func GetPodVolumeByName(podSpec *corev1.PodSpec, name string) *corev1.Volume {
moved to `internal/utils/kubernetes/pod_utis.go`.

2022-09-06 05:45 UTC, mlavacca reviewed
looks good, a couple of minor nits

2022-09-06 05:45 UTC, mlavacca commented on controllers/gateway_controller.go
> +		debug(log, "controlplane should be updated to expected state", controlplane)
```suggestion
```

2022-09-06 05:45 UTC, mlavacca commented on controllers/gateway_controller.go
> +		debug(log, "controlplane config is out of date, updating", gateway)
```suggestion
		trace(log, "controlplane config is out of date, updating", gateway)
```

2022-09-06 05:51 UTC, mlavacca commented
@randmonkey I believe this PR fixes this issue too: https://github.com/Kong/gateway-operator/issues/183 WDYT?

2022-09-06 06:26 UTC, randmonkey commented
> @randmonkey I believe this PR fixes this issue too: #183 WDYT?

I think so.

2022-09-06 07:50 UTC, mlavacca approved these changes

2022-09-06 08:28 UTC, merged