[WIP] feat(validation) add validation for dataplane
Kong/gateway-operator pull request #39
Opened 2022-06-13 10:00 UTC by randmonkey

**What this PR does / why we need it**:

Added validator interface and dataplane validation for dbMode in Reconciler and Webhook.

**Which issue this PR fixes** 
#13

**Special notes for your reviewer**:
Work in progress, still working on adding a certificate(probably by `certManager`) for webhook server

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect significant changes

2022-06-13 10:26 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/Kong/gateway-operator?pullRequest=39) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/Kong/gateway-operator?pullRequest=39) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/Kong/gateway-operator?pullRequest=39) it.</sub>

2022-06-13 16:39 UTC, shaneutt requested changes
Early review, as requested. Things are looking really good! I have a few comments for your considerations. :vulcan_salute:

2022-06-13 16:39 UTC, shaneutt commented on controllers/dataplane_controller.go
> +	err = v.Validate(dataplane)
as we only need to use the validator once and it's constructor doesn't return an error, are you opposed to daisy-chaining the call to save a line?

```suggestion
	err = dataplanevalidation.NewValidator(r.Client).Validate(dataplane)
```

2022-06-13 16:39 UTC, shaneutt commented on controllers/dataplane_controller.go
> +		debug(log, "failed to validate dataplane: error "+err.Error(), dataplane)
across KIC and other codebases of ours, it's pretty common to just put the error itself after the colon, if that sounds reasonable to you:

```suggestion
		debug(log, "failed to validate dataplane: "+err.Error(), dataplane)
```

2022-06-13 16:39 UTC, shaneutt commented on controllers/dataplane_controller.go
> +		r.eventRecorder.Event(dataplane, "Warning", "ValidationFailed", err.Error())
:+1: I'm glad that you took the time to add an event recorder and emit events about this. This reminds me of https://github.com/Kong/kubernetes-ingress-controller/issues/2195 where we are in need of something like this for the KIC.

2022-06-13 16:39 UTC, shaneutt commented on controllers/dataplane_controller.go
> +		return ctrl.Result{Requeue: false}, nil
So we have a log entry AND an event for this, and that's good but we should keep in mind that both logs and events are potentially transient. We should update the status of the object as well to reflect the problem: we have the `DataPlaneConditionTypeProvisioned` status condition type already to indicate whether the `DataPlane` object has been provisioned. I think it would be fair to add a new `reason` such as `DataPlaneConditionReasonFailedValidation` and when we get to this point, ensure that the status conditions include a provisioned condition with that reason and `False`, plus a helpful message that indicates the exact validation failure.

2022-06-13 16:39 UTC, shaneutt commented on internal/admission/server.go
> +func NewWebhookServerFromManager(mgr ctrl.Manager) *webhook.Server {
lint: public symbols need godoc comments

2022-06-13 16:39 UTC, shaneutt commented on internal/admission/server.go
> +type Validator interface {
lint: public symbols need godoc comments

2022-06-13 16:39 UTC, shaneutt commented on internal/admission/server.go
> +type RequestHandler struct {
lint: public symbols need godoc comments

2022-06-13 16:39 UTC, shaneutt commented on internal/admission/server.go
> +func NewRequestHandler(logger logrus.FieldLogger) *RequestHandler {
lint: public symbols need godoc comments

2022-06-13 16:39 UTC, shaneutt commented on internal/admission/server.go
> +		Logger:    logger.WithField("a", "b"),
Should we update these fields?

2022-06-13 16:39 UTC, shaneutt commented on internal/admission/server.go
> +func (h *RequestHandler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
lint: public symbols need godoc comments

2022-06-13 16:39 UTC, shaneutt commented on internal/admission/server.go
> +		}
I see you're taking the time to just scaffold out validation for the `ControlPlane` as well while we're already here, :+1:

2022-06-13 16:39 UTC, shaneutt commented on internal/consts/consts.go
> +// -----------------------------------------------------------------------------
```suggestion
// -----------------------------------------------------------------------------

```

2022-06-13 16:39 UTC, shaneutt commented on internal/consts/consts.go
> +	EnvVarKongDatabase = "KONG_DATABASE"
lint: public symbols need godoc comments

2022-06-13 16:39 UTC, shaneutt commented on internal/manager/run.go
> +
lint: I think this blank space is making the linter mad
```suggestion
```

2022-06-13 16:39 UTC, shaneutt commented on internal/manager/run.go
> +	tlsKeyPath := "/tmp/k8s-webhook-server/serving-certs/tls.key"
I take it since this PR is in draft still, this is a temporary hardcoded location and we'll add a dynamic method to import these soon?

2022-06-13 16:39 UTC, shaneutt commented on internal/validation/dataplane/validation.go
> +type Validator struct {
lint: this and many of the public symbols in this file need godoc comments

2022-06-13 16:39 UTC, shaneutt commented on internal/validation/dataplane/validation.go
> +func (v *Validator) ValidateDeployOptions(namespace string, opts *operatorv1alpha1.DeploymentOptions) error {
I appreciate that you did this validation against `DeploymentOptions`, that's going to work to our advantage because the upcoming `GatewayConfiguration` API is going to have to use this validator as well :+1:

2022-06-13 16:39 UTC, shaneutt commented on internal/validation/dataplane/validation.go
> +					}
I agree with the choice to throw an error here :+1: 

It's a bit against the eventual consistency grain of Kubernetes APIs, but if we _didn't_ throw an error here then we would either a) have to validate `ConfigMaps` on creation referenced against `DataPlanes` which reference them (which is a nightmare) or b) we would have to do an extra level of validation during reconcilation once we finally have the values from the `ConfigMaps` pulled, which I think is potentially rough UX.

That said, because this goes against the grain a bit I think it's worth adding a comment here so that future code readers can quickly understand the nuance introduced here:

```suggestion
					// technically it goes slightly against eventual-consistency to throw an error here,
					// but the alternative is that we would need to validate ALL ConfigMaps on create
					// and do relational mapping to DataPlane resources to validate that they aren't
					// going to introduce a new violation, or we would have to do an additional level
					// of validation that could only run during reconcilation.
					err := v.c.Get(context.Background(), namespacedName, cm)
					if err != nil {
						return fmt.Errorf("can't validate referenced configMap %s: %w", cmKeyRef.Name, err)
					}
```

Also as you'll see I suggested an update to the user-facing error message: for something a bit out of the norm like this I think the language we provide to the API caller is very important. Let me know what you think of that suggestion there.

As an aside: ultimately doing this kind of cross-reference validation is a tricky balancing act: upstream might push us _not_ to do it and in a general sense they wouldn't be wrong, but the reality is that a clear error upfront can go a long way for user experience. I think this change strikes a good balance, and the other good thing is it's easy to remove this later if it somehow was causing problems.

2022-06-13 16:39 UTC, shaneutt commented on internal/validation/dataplane/validation.go
> +						return fmt.Errorf("failed to get secret %s in secretRef, error %w", secretRef.Name, err)
Similar to the above comment, I agree with the approach I just think there's enough nuance here that it's worth adding some comments and maybe adjusting the error message for considerations around end-user clarity.

2022-06-13 16:39 UTC, shaneutt commented on internal/validation/dataplane/validation.go
> +	// TODO: if dbMode not found in envVar, search for it in EnvVarFrom.
Don't forget to clean up this TODO :+1:

2022-06-13 16:39 UTC, shaneutt commented on internal/validation/dataplane/validation_test.go
> +}
Just a note that unless I missed it, it doesn't look like we've got this webhook completely hooked up in the kustomization `config/` configurations. Let's make sure we do that, and we add a basic webhook test to the E2E tests before we merge (e.g. the E2E tests just deploy via kustomize, ensure that the webhook is created and working properly by adding a call to try and create an invalid `DataPlane` to an existing test).

2022-06-13 20:31 UTC, jrsmroz commented on internal/validation/dataplane/validation.go
> +					}
I actually find this deeply nested code hard to follow.

2022-06-13 22:48 UTC, shaneutt commented on internal/validation/dataplane/validation.go
> +					}
> I actually find deeply nested conditional code hard to follow.

@jrsmroz It seems we should phrase that feedback an action: @randmonkey in addition to some comments and some updated error messages would you mind please refactoring this into more smaller tightly purposes functions/methods please?

2022-06-14 03:43 UTC, randmonkey commented on internal/admission/server.go
> +		Logger:    logger.WithField("a", "b"),
Sorry, this is just a temporary thing,

2022-06-14 03:44 UTC, randmonkey commented on internal/consts/consts.go
> +// -----------------------------------------------------------------------------
empty line here?

2022-06-14 03:45 UTC, randmonkey commented on internal/manager/run.go
> +	tlsKeyPath := "/tmp/k8s-webhook-server/serving-certs/tls.key"
I think we would define the default paths as constants.

2022-06-14 05:21 UTC, randmonkey commented on controllers/dataplane_controller.go
> +	err = v.Validate(dataplane)
Yep, since there are currently no error returned from `NewValidator`, it is better to use a chained calling.

2022-06-14 06:13 UTC, randmonkey commented on controllers/dataplane_controller.go
> +		return ctrl.Result{Requeue: false}, nil
Maybe we could unify the logging format we are using. there are already 2 formats of logs:
```
{"level":"info","ts":1655179827.2874749,"logger":"controller-runtime.metrics","msg":"Metrics server is starting to listen","addr":"127.0.0.1:8080"}
```
from `zap`
```
I0614 04:10:27.288748       1 leaderelection.go:248] attempting to acquire leader lease kong-system/a7feedc84.konghq.com...
```
from `klog`(logging packages inside kubernetes)
and importing `logrus` brings another format:
```
time="2022-06-14T04:15:18Z" level=error msg="failed to run validation" component=validation-server
``` 
How about unifying to `zap`?

2022-06-14 13:42 UTC, shaneutt commented on controllers/dataplane_controller.go
> +		return ctrl.Result{Requeue: false}, nil
It still occurs to me that we would want a status condition for this of type `DataPlaneConditionTypeProvisioned` and `metav1.ConditionFalse` and an explanation therein.

2022-06-14 13:43 UTC, shaneutt commented on internal/admission/server.go
> +		Logger:    logger.WithField("a", "b"),
ok :+1:

2022-06-14 13:44 UTC, shaneutt commented on internal/manager/run.go
> +	tlsKeyPath := "/tmp/k8s-webhook-server/serving-certs/tls.key"
That's fine, and I know this is still draft too. Let's try to match how KIC does this to some degree when we get back around to it. :+1:

2022-06-24 18:13 UTC, jrsmroz commented on controllers/dataplane_controller.go
> +		return ctrl.Result{Requeue: false}, nil
+1 for unifying logging format.

2022-06-29 14:49 UTC, shaneutt requested changes
Looking good, I do have a few comments let me know your thoughts.

2022-06-29 14:49 UTC, shaneutt commented on internal/validation/dataplane/validation.go
> +		return "", false, fmt.Errorf("failed to get configMap %s in configMapKeyRef, error %w", cmKeyRef.Name, err)
commonly we use a colon to separate the messaging about the error from the error itself in a wrapped error as this usually ends up being a pretty clear delineation:

```suggestion
		return "", false, fmt.Errorf("failed to get configMap %s in configMapKeyRef: %w", cmKeyRef.Name, err)
```

2022-06-29 14:49 UTC, shaneutt commented on internal/validation/dataplane/validation.go
> +		return "", false, fmt.Errorf("failed to get secret %s in secretRef, error %w", secretKeyRef.Name, err)
```suggestion
		return "", false, fmt.Errorf("failed to get secret %s in secretRef: %w", secretKeyRef.Name, err)
```

2022-06-29 14:49 UTC, shaneutt commented on internal/validation/dataplane/validation.go
> +		return "", false, fmt.Errorf("failed to get configMap %s in configMapRef, error %w", cmRef.Name, err)
```suggestion
		return "", false, fmt.Errorf("failed to get configMap %s in configMapRef: %w", cmRef.Name, err)
```

2022-06-29 14:49 UTC, shaneutt commented on internal/validation/dataplane/validation.go
> +	// find key in Data that would become `KONG_DATABASE` after concatated to the prefix.
```suggestion
	// find the key in the Data that would become `KONG_DATABASE` after concatenation with the prefix.
```

2022-06-29 14:49 UTC, shaneutt commented on test/integration/suite_test.go
> +	webhookServerIP      = ""
Why not pull this directly from the env?

```suggestion
	webhookServerIP      = os.Getenv("GATEWAY_OPERATOR_WEBHOOK_IP")
```

2022-06-29 14:49 UTC, shaneutt commented on test/integration/suite_test.go
> +	}
Does this need to be separated from the code above on line 88? It seems like it's all related so perhaps we can create a separate function that's responsible for all the webhook and webhook-cert related steps?

2022-06-29 14:49 UTC, shaneutt commented on test/integration/suite_test.go
> +	}
Similar to above comments, it seems if we just combined this with other webhook related setup it would help improve clarity in the suite, and I'm also not seeing the separation as necessary?

2022-06-29 14:49 UTC, shaneutt commented on test/integration/util_test.go
> +func getFirstNonLoopbackIP() (string, error) {
Given that this is a testing environment, any reason we can simply listen on `0.0.0.0` here to always ensure we're listening on the outside routable network even if the networking configuration of the testing environment were to be changed down the road?

2022-07-08 09:49 UTC, randmonkey commented on controllers/dataplane_controller.go
> +		return ctrl.Result{Requeue: false}, nil
updated.

2022-07-08 09:49 UTC, randmonkey commented on controllers/dataplane_controller.go
> +		debug(log, "failed to validate dataplane: "+err.Error(), dataplane)
updated to `info()` here.

2022-07-08 09:50 UTC, randmonkey commented on controllers/dataplane_controller.go
> +
removed the annotations here and updated in `controllers/dataplane_controller_rbac.go` .

2022-07-08 09:52 UTC, randmonkey commented on controllers/dataplane_controller_reconciler_utils.go
> +
Fixed. The current implementation goes as follow:
- if the condition with `DataPlaneConditionTypeProvisioned` exists and is not the same as expected, change it to the expected condition and update the status.
- if the condition with `DataPlaneConditionTypeProvisioned` does not exist, append our expected condition, and update the status.

2022-07-08 09:53 UTC, randmonkey commented on internal/validation/dataplane/validation.go
> +		return "", false, fmt.Errorf("failed to get secret %s in secretRef, error %w", secretKeyRef.Name, err)
fixed.

2022-07-08 10:00 UTC, randmonkey commented on internal/validation/dataplane/validation.go
> +	// validata db mode.
fixed.

2022-07-08 10:00 UTC, randmonkey commented on internal/validation/dataplane/validation.go
> +		return "", false, fmt.Errorf("failed to get configMap %s in configMapKeyRef, error %w", cmKeyRef.Name, err)
updated, and the same for the following.

2022-07-08 10:01 UTC, randmonkey commented on test/integration/suite_test.go
> +	webhookServerIP      = ""
updated

2022-07-08 10:02 UTC, randmonkey commented on test/integration/suite_test.go
> +	}
fixed for this. put the getting IP and generating certificates into one block.

2022-07-08 10:30 UTC, randmonkey commented on test/integration/suite_test.go
> +	}
I think the separation is necessary.  generating certificates should be done before we run controller manager, and waiting for webhook server to be available should be happen after controller manager start.

2022-07-08 10:33 UTC, randmonkey commented on test/integration/util_test.go
> +func getFirstNonLoopbackIP() (string, error) {
Yes, our service do listen on `0.0.0.0`. But getting a specific IP is still necessary. The IP  is used for generating certificates and for clients to access. We need to specify an IP when we generate the certificate requests, and give an IP for clients to access.

2022-07-08 13:56 UTC, randmonkey commented
`make lint` complains 
```
INFO fixer took 0s with no stages                 
controllers/utils.go:26:92: directive `//nolint:deadcode,unused //FIXME` is unused for linter "deadcode" (nolintlint)
```
I searched for this error message and tried to fix it, but no effect. @shaneutt do you know how to fix the lint issue?

2022-07-08 14:44 UTC, pmalek commented
> `make lint` complains
> 
> ```
> INFO fixer took 0s with no stages                 
> controllers/utils.go:26:92: directive `//nolint:deadcode,unused //FIXME` is unused for linter "deadcode" (nolintlint)
> ```
> 
> I searched for this error message and tried to fix it, but no effect. @shaneutt do you know how to fix the lint issue?

@randmonkey remove `deadcode` from this `nolint` comment. This code is in fact not "dead": this **is** being used in here https://github.com/randmonkey/gateway-operator/blob/issue13_validation/controllers/dataplane_controller.go#L82

2022-07-08 18:47 UTC, shaneutt requested changes
I asked for this previously but the conversation was marked resolved without resolution: we need to add a test that ensures the webhook is functioning properly when the operator is deployed via kustomize (e.g. the contents in `config/`). I want to repeat my suggestion that we should add an E2E test that deploys the operator via `kustomize` and verifies that the webhook is functioning there, as this will help us prevent regressions. The KIC has some examples of deploying via kustomize for E2E tests which may be helpful.

2022-07-08 18:47 UTC, shaneutt commented on controllers/dataplane_controller_reconciler_utils.go
> +	// TODO: should we compare `ObservedGeneration` here?
We should resolve this TODO, and I think the answer to the question is ultimately "no", it doesn't seem like what we're doing here is actually checking if it's the _exact_ same condition but instead if the non-database related fields are the same. We should update the function docs and maybe the name to reflect that.

2022-07-13 08:58 UTC, randmonkey commented
> I asked for this previously but the conversation was marked resolved without resolution: we need to add a test that ensures the webhook is functioning properly when the operator is deployed via kustomize (e.g. the contents in `config/`). I want to repeat my suggestion that we should add an E2E test that deploys the operator via `kustomize` and verifies that the webhook is functioning there, as this will help us prevent regressions. The KIC has some examples of deploying via kustomize for E2E tests which may be helpful. 
 Added e2e  tests in the latest PR. Because the operator image has not updated, the e2e fails now. If image `richardyi/kong-gateway-operator:20220713-1` is used in e2e tests, the test would be passed. The further things to do about e2e is to build and push a new image before running tests.

2022-07-13 18:55 UTC, shaneutt requested changes

2022-07-14 07:28 UTC, randmonkey commented on test/e2e/webhook_test.go
> +}
added steps of building image and loading image in e2e tests.

2022-07-14 13:46 UTC, shaneutt requested changes
I think we're getting _very_ close with this PR but I do think we have at least one remaining blocker: the way we're handling certificates for the webhook isn't portable.

I would suggest that we take a look at Gateway APIs for an example of how to manage webhook and certs in a native manner:

https://github.com/kubernetes-sigs/gateway-api/blob/main/config/webhook/certificate_config.yaml

2022-07-14 13:46 UTC, shaneutt commented on .github/workflows/tests.yaml
> +        KONG_TEST_GATEWAY_OPERATOR_IMAGE_LOAD: gateway-operator:e2e-${{ github.sha }}
:+1: thanks for adding the image build and load

2022-07-14 13:46 UTC, shaneutt commented on config/certificate/issuer.yaml
> +  selfSigned: {}
We can't rely on cert-manager to be available in all cases, so adding this will potentially cause deployment to fail. We need to manage certificates for the webhook in a fully native manner.

2022-07-15 07:49 UTC, randmonkey commented on config/certificate/issuer.yaml
> +  selfSigned: {}
removed those certmanager` configurations and used the same way to generate certificates as in Gateway API project.

2022-07-15 07:49 UTC, randmonkey commented on Makefile
> +
fixed.

2022-07-15 15:31 UTC, shaneutt submitted a review, later dismissed
Looking good. Ultimately this PR has gotten quite large and so I imagine that there's still quite a few more things that we could touch up, but since we're still in a nice cocooned early development stage I think it's reasonable to take this value in its current state and iterate on it as we run into problems so :heavy_check_mark: let's get this merged.

Before merging however, please resolve all `TODO` comments: let's not leave errant `TODO` comments. They either should be resolved in the same PR _or_ at least create a follow up issue and link it in the comment so that they don't get out of band.

2022-07-15 15:31 UTC, shaneutt commented on test/e2e/utils_test.go
> +	// e.g localhost:32000/kong/gateway-operator:xxx
Let's add an link a github issue to this TODO so that it's not lost

2022-07-15 15:50 UTC, pmalek commented on test/e2e/utils_test.go
> +	return nil
```suggestion
	return os.WriteFile("../../config/default/kustomization.yaml", newBuf, os.ModeAppend)
```

Apart from the suggestion I'm kind of worried about the implicit dependency on this file. Is this being used from elsewhere? 

Also, not trying to pick on the name here but `setOperatorImage` doesn't really say much about the side effect I've mentioned about. There's also no comment on it which might exacerbate the surprise effect.

Maybe we could write that new kustomization file to a temp file and pass its path around and then ensure at the end of the tests that we clean it up? This doesn't have to happen in this PR but I'd really like to see this change given what I've described above.

2022-07-15 15:50 UTC, pmalek commented on test/e2e/utils_test.go
> +// namespace create a namespace for a test case, and clean it up after the test finishes.
```suggestion
// namespace creates a namespace for a test case and cleans it up after the test finishes.
```

Actually, this does not clean this up but it returns a `func` that can clean it up.

What you could do here is use `t.Cleanup()` to register the cleanup like so:

```go
func namespaceForCluster(t *testing.T) *corev1.Namespace {
	namespaceForTestCase, err := clusters.GenerateNamespace(ctx, env.Cluster(), t.Name())
	require.NoError(t, err) // this or return an error but NoError is "equivalent" to exitOnErr(err)

	t.Cleanup(func(){
		assert.NoError(t, clusters.CleanupGeneratedResources(ctx, env.Cluster(), t.Name()))
	})

	return namespaceForTestCase
}
```

2022-07-15 15:57 UTC, shaneutt commented on test/e2e/utils_test.go
> +	return nil
Good point. I agree that it would be nice if we could make a tempfile for this purpose instead of overwriting files in the repository before we ship this, as inevitably someone is going to accidentally commit those changes at some point.

2022-07-18 03:15 UTC, randmonkey commented on test/e2e/utils_test.go
> +	// e.g localhost:32000/kong/gateway-operator:xxx
added issue #88.

2022-07-18 03:15 UTC, randmonkey commented on test/e2e/utils_test.go
> +	return nil
fixed. For the second question, I am looking at kustomize to find out how to do it.

2022-07-18 03:16 UTC, randmonkey commented on test/e2e/utils_test.go
> +// namespace create a namespace for a test case, and clean it up after the test finishes.
fixed comments.

2022-07-18 08:55 UTC, pmalek submitted a review, later dismissed

2022-07-18 08:55 UTC, pmalek commented on Makefile
> +# the same as e2e, but used for github actions because the github workflow for e2e would modify contents of manifests in `config`.
I don't understand this comment given that those 2 targets are exactly the same. Do you mind explaining further?

2022-07-18 08:55 UTC, pmalek commented on config/admission_webhook/certificate_config.yaml
> +        runAsUser: 2000
EOL

2022-07-18 08:55 UTC, pmalek commented on config/admission_webhook/kustomization.yaml
> +- validating_webhook.yaml
EOL

2022-07-18 08:55 UTC, pmalek commented on config/default/manager_webhook_certificates_patch.yaml
> +
EOL

2022-07-18 08:55 UTC, pmalek commented on internal/validation/dataplane/validation.go
> +	return nil
```suggestion
	return v.ValidateDeployOptions(dataplane.Namespace, &dataplane.Spec.DeploymentOptions)
```

2022-07-18 08:55 UTC, pmalek commented on hack/generate-certificates-openssl.sh
> + -CAcreateserial -out ${cert_dir}/tls.crt -extensions v3_ext -extfile ${cert_dir}/webhook_ext.cnf
EOL

2022-07-18 08:55 UTC, pmalek commented on hack/generate-certificates-openssl.sh
> +#!/bin/bash
I'm wondering if this wouldn't be beneficial to write in Go to avoid the possible problems of running bash scripts from Go. This way we'll have way more control over subprocess (function) runtime, return codes etc. 🤔

2022-07-18 08:55 UTC, pmalek commented on internal/admission/server.go
> +	}
The `nil` check can be the very first thing done in this `func`.

```suggestion
	if req == nil {
		return &admissionv1.AdmissionResponse{
			Allowed: false
			Result: &metav1.Status{
				Code:    http.StatusBadRequest,
				Reason:  metav1.StatusReasonBadRequest,
				Message: "empty request",
				Status:  metav1.StatusFailure,
			}
		}, nil
	}
	
	var (
		response admissionv1.AdmissionResponse
		ok = true
		msg string
		deserializer = codecs.UniversalDeserializer()
	)
```

2022-07-18 08:55 UTC, pmalek commented on internal/admission/validator.go
> +	return nil
```suggestion
	return v.dataplaneValidator.Validate(&dataPlane)
```

2022-07-18 08:55 UTC, pmalek commented on test/integration/suite_test.go
> +			exitOnErr(getIPErr)
This block doesn't look right. `getIPErr` is never assigned to.

2022-07-18 08:55 UTC, pmalek commented on test/integration/suite_test.go
> +		// get IP for genrating certificate and for clients to access.
```suggestion
		// get IP for generating certificate and for clients to access.
```

2022-07-18 08:55 UTC, pmalek commented on test/integration/suite_test.go
> +	runWebhookTests = (os.Getenv("RUN_WEBHOOK_TESTS") == "true")
Can we extract this whole block responsible for setup of webhook to a separate func, and give it a parameter of `RUN_WEBHOOK_TESTS` env explaining in the comment how to use it? (the `"true"` value will ....)

2022-07-18 10:47 UTC, randmonkey commented on test/integration/suite_test.go
> +			exitOnErr(getIPErr)
fixed.

2022-07-18 10:47 UTC, randmonkey commented on internal/admission/validator.go
> +	return nil
updated.

2022-07-18 10:47 UTC, randmonkey commented on test/integration/suite_test.go
> +		// get IP for genrating certificate and for clients to access.
fixed

2022-07-18 10:50 UTC, randmonkey commented on test/integration/suite_test.go
> +	runWebhookTests = (os.Getenv("RUN_WEBHOOK_TESTS") == "true")
I tried to move all webhook related code into one function, but it had to be separated into 2 parts:
 - generating webhook certificates, which must be run before operator started
 - waiting for webhook to be available, which must be run after operator started. 
So the code related to webhook has to be seperated into 2 parts, or add some sync mechanism to keep the order.

2022-07-18 10:50 UTC, randmonkey commented on hack/generate-certificates-openssl.sh
> + -CAcreateserial -out ${cert_dir}/tls.crt -extensions v3_ext -extfile ${cert_dir}/webhook_ext.cnf
fixed

2022-07-18 10:51 UTC, randmonkey commented on internal/validation/dataplane/validation.go
> +	return nil
This is prepared to add more validations. I added comments here.

2022-07-18 10:54 UTC, randmonkey commented on hack/generate-certificates-openssl.sh
> +#!/bin/bash
generating a self-signed certificate set by pure Go has much less practice. Seems @shaneutt  has implemented one: https://medium.com/@shaneutt/create-sign-x509-certificates-in-golang-8ac4ae49f903. But generating certificates by openssl command has much more references. So I decided to use `openssl` command here first.

2022-07-18 10:55 UTC, randmonkey commented on config/default/manager_webhook_certificates_patch.yaml
> +
fixed

2022-07-18 10:55 UTC, randmonkey commented on config/admission_webhook/kustomization.yaml
> +- validating_webhook.yaml
fixed

2022-07-18 10:55 UTC, randmonkey commented on config/admission_webhook/certificate_config.yaml
> +        runAsUser: 2000
fixed.

2022-07-18 10:56 UTC, randmonkey commented on internal/admission/server.go
> +	}
updated.

2022-07-18 10:56 UTC, randmonkey commented on Makefile
> +# the same as e2e, but used for github actions because the github workflow for e2e would modify contents of manifests in `config`.
removed the duplicate one.

2022-07-21 17:20 UTC, pmalek commented on test/integration/suite_test.go
> +	runWebhookTests = (os.Getenv("RUN_WEBHOOK_TESTS") == "true")
I might be not understanding things but I believe 

- your first bullet point is covered by the the code in `if` clause below
- second bullet point is already covered by the `if` statement on line 165

My suggestion in that case is to move the first block ("initialization code") into a separate func: similarly as `waitForWebhook` does.

The reason I'm trying to push this sort of refactoring of this is to prevent bloating of `TestMain` here ( which IMO is already getting pretty hard to reason about ). Ideally this should be refactored into calling a handful of named functions at maximum.

2022-07-21 17:20 UTC, pmalek commented on test/integration/suite_test.go
> +func waitForWebhook(ctx context.Context, ip string, port int) error {
This in my view, shouldn't be called `waitForWebhook` but `isTCPPortOpen` or similar.

I believe this needs some further explanation in a godoc here.

Additionally: can't we use an HTTP GET here? Wouldn't that translate better into "checking if webhook is ready"? Is that because of certificates and the need to not verify them on such request?

2022-07-21 17:20 UTC, pmalek commented on test/e2e/utils_test.go
> +func namespace(t *testing.T) (*corev1.Namespace, func()) {
- Perhaps we could rename this to something indicating what's this going to do? Like `createNamespaceForTest()` or similar? `namespace` might also be a quite commonly used identifier in tests conflicting with this functions name.
- I believe I have already suggested this: can't we use `t.Cleanup()` here instead of returning the cleanup function? It would make the house keeping automated and less error prone. WDYT?

2022-07-21 17:20 UTC, pmalek commented on test/integration/suite_test.go
> +		exitOnErr(manager.Run(cfg))
Can't we leave this as it was, i.e. not running this in a goroutine and hence requiring the caller to do `go startControllerManager()` which makes it obvious to the caller that an extra goroutine will be spawned?

Oh and wouldn't this break the stdout code above which via `defer out.Close()` will close the stdout's file and prevent logging from happening?

2022-07-21 17:20 UTC, pmalek commented on test/e2e/utils_test.go
> +	return os.WriteFile("../../config/default/kustomization.yaml", newBuf, os.ModeAppend)
I'm really, really, really hesitant about introducing this implicit files manipulation. 

Beside the fact that this will leave the working directory dirty (right?), the file paths that are used here might quickly become outdated. Ideally these tests would get their own templates to manipulate (as `const`s or in dedicated tests directories).

We can create an issue to address this in the future if we're pressed to merge this PR.

2022-07-22 08:35 UTC, randmonkey commented on test/integration/suite_test.go
> +	runWebhookTests = (os.Getenv("RUN_WEBHOOK_TESTS") == "true")
Moved the initialization code for webhook to `prepareWebhook` function.

2022-07-22 08:36 UTC, randmonkey commented on test/integration/suite_test.go
> +func waitForWebhook(ctx context.Context, ip string, port int) error {
updated the `waitForWebhook` to use an HTTP GET, and any response is judged as ready.

2022-07-22 08:37 UTC, randmonkey commented on test/integration/suite_test.go
> +		exitOnErr(manager.Run(cfg))
updated.

2022-07-22 08:44 UTC, pmalek commented on test/e2e/utils_test.go
> +	}
What about using the `t.Cleanup()`? (Github swallowed my comments ): )

2022-07-22 08:52 UTC, pmalek commented on test/e2e/utils_test.go
> +
```suggestion
```

2022-07-22 08:52 UTC, pmalek commented on test/e2e/utils_test.go
> +func setOperatorImage() error {
I think this comment is not complete, is it?

2022-07-22 08:52 UTC, pmalek commented on test/e2e/utils_test.go
> +func namespace(t *testing.T) (*corev1.Namespace, func()) {
Ok got it. What would be the situation where you want to decide the leave the namespace? Debugging? That would require us to modify the code in order to leave the namespace and not trigger the returned cleanup function, right? So basically this would be the same as having `t.Cleanup()` in place and also modifying it in source code (e.g. commenting out?) to prevent the cleanup.

I'm going to pass on the idea of changing this for the sole reason that given that we use some sort of a framework like KTF we can then hook this cleanup func into it and do decision making whether to perform the cleanup there.

2022-07-22 08:52 UTC, pmalek commented on test/e2e/utils_test.go
> +	}
Nevermind, found it. Let's disregard my comment here.

2022-07-22 08:58 UTC, randmonkey commented on test/e2e/utils_test.go
> +	return os.WriteFile("../../config/default/kustomization.yaml", newBuf, os.ModeAppend)
- I agree that we should not affect the working directory when we run tests, so I copied the original content to a backup file and restore it back. Kustomize does not support to use an alternative kustomization file in a directory: [kustomize#4659](https://github.com/kubernetes-sigs/kustomize/issues/4659) so we could only use the backup method to keep the work directory clean.
- I think we would **NOT** use own "templates"(in fact, kustomize is not a template: [kustomize introduction](https://kubernetes.io/blog/2018/05/29/introducing-kustomize-template-free-configuration-customization-for-kubernetes/)  ) for each test case. The e2e test is used to verify that our manifests(generated from kustomization from `config` directory) and code is OK for its usage. So all the test cases are using the same kustomization directory.

2022-07-22 08:58 UTC, randmonkey commented on test/e2e/utils_test.go
> +	}
I think I have explained.

2022-07-22 09:00 UTC, randmonkey commented on test/e2e/utils_test.go
> +func setOperatorImage() error {
updated. Forgot to add it before.

2022-07-22 09:00 UTC, randmonkey commented on test/e2e/utils_test.go
> +
fixed.

2022-07-22 09:33 UTC, randmonkey commented on test/e2e/utils_test.go
> +func restoreustomizationFile() error {
fixed.

2022-07-22 10:33 UTC, pmalek commented
I've started a discussion on files modification in tests in https://github.com/Kong/team-k8s/discussions/230 which I've touched on in several comments here.

Other than that I feel this is OK: apart from being quite big :) I'll let other 👍 / 👎 this.

2022-07-22 14:15 UTC, shaneutt approved these changes
Again, I'm sure due to the size of this we're probably going to end up having to come back to some of the pieces, but at this stage in the project it is OK to take a fix-it-forward mentality, and the core of what we're adding here is good. I advocate that we merge and then fix forward :+1:

2022-07-22 14:25 UTC, merged

2022-07-22 14:25 UTC, shaneutt commented
CI was being cranky about the license tests. There was no problem, so I admin merged :+1: