feat: GatewayConfiguration API
Kong/gateway-operator pull request #43
Opened 2022-06-22 19:00 UTC by shaneutt

**What this PR does / why we need it**:

This adds a `GatewayConfiguration` API which can be used to add configuration on `Gateway` resources.

**Which issue this PR fixes**

Resolves #33

**PR Readiness Checklist**:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect significant changes

2022-06-24 19:24 UTC, shaneutt commented on api/v1alpha1/gatewayconfiguration_types.go
> +	TargetRef GatewayTargetReference `json:"targetRef"`
The reason this is here is that I wasn't liking the UX and I preferred being able to configure individual `Gateways`. That said doing it this way is painful from an RBAC perspective so I'm OK with taking this approach for now. Changed to use `ParametersReference` in the most recent push.

2022-06-24 19:25 UTC, shaneutt commented on api/v1alpha1/shared_types.go
> +	GatewayConfigurationTargetKindGatewayClass GatewayConfigurationTargetKind = "Gatewayclass"
Fixed in the most recent push.

2022-06-24 19:25 UTC, shaneutt commented on api/v1alpha1/gatewayconfiguration_types.go
> +	ControlPlaneSpec *ControlPlaneSpec `json:"controlplaneDeploymentOptions,omitempty"`
Fixed in the most recent push.

2022-06-24 19:25 UTC, shaneutt commented on controllers/controlplane_controller.go
> +		Named("controlplane").
Fixed in the most recent push.

2022-06-24 19:26 UTC, shaneutt commented on controllers/controlplane_controller_utils.go
> +		}
Since this was only moved around, but didn't originate from this PR and with #21 already poised as a follow-up, I would like to hold since we'll just be changing this again in #21 anyway.

2022-06-24 19:26 UTC, shaneutt commented on controllers/dataplane_controller_utils.go
> +	"KONG_DATABASE":               "off",
Fixed in the most recent push.

2022-06-24 19:26 UTC, shaneutt commented on controllers/dataplane_controller_utils.go
> +	"KONG_PROXY_LISTEN":           fmt.Sprintf("0.0.0.0:%d, 0.0.0.0:%d http2 ssl", defaultKongHTTPPort, defaultKongHTTPSPort),
Fixed in the most recent push.

2022-06-24 19:27 UTC, shaneutt commented on controllers/dataplane_controller_utils.go
> +	"KONG_LUA_PACKAGE_PATH":       "/opt/?.lua;/opt/?/init.lua;;",
No reason just copypasta. Removed.

2022-06-24 19:34 UTC, shaneutt commented on controllers/dataplane_controller_utils.go
> +func setDataPlaneDefaults(spec *operatorv1alpha1.DataPlaneSpec, dontOverride map[string]struct{}) {
Yes this is already being done, but _only_ in the Gateway controller: if you set fields (with the exception of a couple of very specific ones) they wont be overwritten by defaults but the rest of the defaults will be merged in.

We don't do this here in the DataPlane controller however: these are intended to be more raw APIs, end-users shouldn't really need to use these directly so at least for now I haven't been focusing on adding these kinds of automations at this level, instead focusing on that at the `Gateways` level.

2022-06-24 19:34 UTC, shaneutt commented on controllers/gateway_controller.go
> +	// watch for updates to Gatewayclasses, if any GatewayClasses change, enqueue
:+1:

2022-06-24 19:56 UTC, shaneutt commented on api/v1alpha1/gatewayconfiguration_types.go
> +	ControlPlaneSpec *ControlPlaneSpec `json:"controlplaneDeploymentOptions,omitempty"`
Yes I agree, I glossed over this one when I was self-reviewing. The sub-reference now excludes `GatewayClass` OR `IngressClass` from the `GatewayConfiguration` perspective.

2022-06-24 20:44 UTC, shaneutt commented
Marking this as DO-NOT-MERGE because while it's ready for general review, I have a few more tests I'm going to push up before we merge it.

2022-06-27 17:52 UTC, rainest commented on controllers/dataplane_controller_utils.go
> +func setDataPlaneDefaults(spec *operatorv1alpha1.DataPlaneSpec, dontOverride map[string]struct{}) {
Right, the intended audience for this is us, when writing other parts of the controller. If I want to add functionality that, for example, sets `KONG_LUA_PACKAGE_PATH` to implement something like the chart's "give me a ConfigMap with plugin source and I'll make sure the proxy can use it" feature, I just set it, without worrying about needing to build a `dontOverride` set.

If there's something that collects internal requests to set a envvar, applies them, and then applies user-supplied values last, I can be confident that the user setting takes precedence without having to build/check state information about whether they set it.

2022-06-27 18:33 UTC, shaneutt commented on controllers/dataplane_controller_utils.go
> +func setDataPlaneDefaults(spec *operatorv1alpha1.DataPlaneSpec, dontOverride map[string]struct{}) {
So just so I'm clear: what action to you want to see happen here in order to consider this resolved?

2022-06-27 20:05 UTC, rainest requested changes
https://github.com/Kong/gateway-operator/pull/45 covers most of the new change requests. I still think we should invert the order of environment building so that overrides are the last thing we overlay atop any other values the operator has injected, but that's a bit more complex to rip out, so it can be deferred.

2022-06-27 20:17 UTC, rainest commented on controllers/dataplane_controller_utils.go
> +func setDataPlaneDefaults(spec *operatorv1alpha1.DataPlaneSpec, dontOverride map[string]struct{}) {
Currently, https://github.com/Kong/gateway-operator/blob/a5d149e7e36e5783d463b9ea31f9db42932a632c/controllers/dataplane_controller_utils.go#L99-L100 builds the initial Deployment with Env from user configuration, and https://github.com/Kong/gateway-operator/blob/a5d149e7e36e5783d463b9ea31f9db42932a632c/controllers/gateway_controller.go#L516-L526 overlays defaults over top of them, but needs to check which defaults it should skip. Resolution inverts that order, so that the Deployments start with Env from a static default and the controller overlays the user configuration over top of them, without need to check it should skip.

Refactoring that looks non-trivial and requires changing existing code though, so I'll move that to a new issue.

2022-06-27 21:19 UTC, shaneutt commented on controllers/gateway_controller.go
> +	}
https://github.com/Kong/gateway-operator/pull/45

2022-06-27 21:19 UTC, shaneutt commented on controllers/gateway_controller.go
> +			string(gatewayClass.Spec.ParametersRef.Group) == "gateway-operator.konghq.com" &&
https://github.com/Kong/gateway-operator/pull/45

2022-06-27 21:30 UTC, shaneutt commented on controllers/gateway_controller.go
> +}
No you're right, it was superfluous as the map function already reduced for this condition. This is now removed in an upcoming push.

2022-06-27 23:40 UTC, shaneutt commented on api/v1alpha1/gatewayconfiguration_types.go
> +}
fixed in f05b80498abe15ba7b79b46f605e77971a556601

2022-06-27 23:40 UTC, merged

2022-06-27 23:42 UTC, shaneutt commented
This merged without CI done, turns out the repository hadn't been configured fully yet so the auto-merge closed it. I've updated the settings for for PR's against `main` to catch this in the future.