WIP:  fix: controlplane without dataplane remains dormant
Kong/gateway-operator pull request #51
Opened 2022-07-01 17:53 UTC by jrsmroz

**What this PR does / why we need it**:

When control plane is created without dataplane, the control plane deployment stays paused (scaled to 0 replicas).

**Which issue this PR fixes**

Fixes #32

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect significant changes

2022-07-01 17:59 UTC, pmalek commented
One comment before we get to the review stage with this PR: if the state of the PR is still in progress - or in other words it's a draft - please make it so by marking it as draft in Github's UI 🙏

2022-07-01 20:02 UTC, jrsmroz commented
> One comment before we get to the review stage with this PR: if the state of the PR is still in progress - or in other words it's a draft - please make it so by marking it as draft in Github's UI 🙏

Hah, sorry. After to many years of work with gitlab I'm used to WIP prefix that does the same, but automatically.

2022-07-07 20:39 UTC, shaneutt requested changes
Just a few small comments :+1:

2022-07-07 20:39 UTC, shaneutt commented on controllers/controlplane_controller.go
> +			debug(log, "conflict found when updating ControlPlane resource, retrying", controlplane)
We've got three different verbs used here which could add to some confusion for future readers:

1. validate
2. ensure
3. update

we should try to update the language to be consistent from line to line, perhaps:

```suggestion
	debug(log, "ensuring that the ControlPlane DataPlane configuration is up to date", controlplane)
	if err = r.ensureDataPlaneConfiguration(ctx, controlplane, nil); err != nil {
		if errors.IsConflict(err) {
			debug(log, "conflict found when trying to ensure ControlPlane configuration was up to date, retrying", controlplane)
```

I'm not positive that the language is quite what we want either, but just to illustrate the point.

2022-07-07 20:39 UTC, shaneutt commented on controllers/controlplane_controller.go
> +		}
:+1:

2022-07-07 20:39 UTC, shaneutt commented on controllers/controlplane_controller.go
> +			debug(log, "DataPlane not set, deployment for ControlPlane is scaled down to 0 replicas", controlplane)
```suggestion
			debug(log, "DataPlane not set, deployment for ControlPlane has been scaled down to 0 replicas", controlplane)
```

2022-07-07 20:39 UTC, shaneutt commented on controllers/controlplane_controller_conditions.go
> +	ControlPlaneConditionReasonNoDataplane = "NoDataplane"
:+1:

2022-07-07 20:39 UTC, shaneutt commented on controllers/controlplane_controller_reconciler_utils.go
> +				updatedConditions = append(updatedConditions, condition)
So it's kinda a pain, but this can technically break: we have a limit of 8 entries per resource set in the API definition. The logic here has to decide which condition(s) to prune. The `Gateway` implementation currently prunes the oldest conditions when a new one needs to be added. I think in time we'll want to add more robust logic for how this is handled and have a decision tree for which conditions need to be present and which don't.

2022-07-07 20:39 UTC, shaneutt commented on controllers/controlplane_controller_reconciler_utils.go
> +				updatedConditions = append(updatedConditions, condition)
Similar to above, we technically need to account for when we would add a condition beyond the limit. For now pruning the oldest may be sane, but in the future we'll probably need to add something more surgical. I'm OK with adding an issue to tackle this fully later.

2022-07-07 20:39 UTC, shaneutt commented on controllers/controlplane_controller_reconciler_utils.go
> +	envDontOverride map[string]struct{},
So I started adding these maps before, but I realized a while ago this isn't how we should be doing this. Ultimately whether or not an env val should be overridden is a function of whether it's a special value or not and whether it's present. Ultimately though no action needs to be taken here because it would bloat the PR with refactoring that this PR is not responsible for, so this is just a note. The follow up for this is https://github.com/Kong/gateway-operator/issues/65.

2022-07-07 20:39 UTC, shaneutt commented on controllers/controlplane_controller_reconciler_utils.go
> +	numReplicasWhenNoDataplane := int32(0)
This would appear to be better as a `const` as there's no need to evaluate or store this value more than once per runtime lifespan.

2022-07-07 20:54 UTC, shaneutt commented on controllers/controlplane_controller_reconciler_utils.go
> +	envDontOverride map[string]struct{},
If you'd like, sure, the behavior for now can be to always override on the controller-owned values and never override on others.

2022-07-07 21:02 UTC, shaneutt commented on controllers/controlplane_controller_reconciler_utils.go
> +	numReplicasWhenNoDataplane := int32(0)
I'm confused: why can't this be a constant?

2022-07-07 21:03 UTC, jrsmroz commented on controllers/controlplane_controller_reconciler_utils.go
> +				updatedConditions = append(updatedConditions, condition)
Shane, as it is now I only seen one condition on dataplane, that is provisioned. We don't keep history for provisioned, it is replaced. I know the logic looks like it's adding new condition, but it is not, it's replacing old condition.
So how come we can reach the limit of 8 ?

2022-07-07 21:09 UTC, shaneutt commented on controllers/controlplane_controller_reconciler_utils.go
> +	numReplicasWhenNoDataplane := int32(0)
Ok I see, you're trying to make a reference to it further down. While that's probably not a huge deal I would still consider it better overall if you made it a constant as this is more fundamentally accurate (nothing should be changing this, it's always going to be zero).

I would suggest instead we _do make this a `const`_ and instead of taking a reference to it directly, we simply use `k8s.io/utils/pointer`, e.g.:

```golang
deployments[0].Spec.Replicas = pointer.Int32Ptr(numReplicasWhenNoDataplane)
```

2022-07-07 21:10 UTC, jrsmroz commented on controllers/controlplane_controller_reconciler_utils.go
> +	numReplicasWhenNoDataplane := int32(0)
Oh, nice trick, will change.

2022-07-07 21:45 UTC, shaneutt commented on controllers/controlplane_controller.go
> +			debug(log, "conflict found when updating ControlPlane resource, retrying", controlplane)
I probably wrote those lines :joy: I do think it's reasonable to challenge everything, but if you don't want to that's fine. Consider this comment resolved at your own discretion as it's really a nitpick anyhow.

2022-07-07 21:46 UTC, jrsmroz commented on controllers/controlplane_controller.go
> +			debug(log, "conflict found when updating ControlPlane resource, retrying", controlplane)
For me, if we can make it better it great. As long as we don't break anything :D

2022-07-07 21:47 UTC, shaneutt commented on controllers/controlplane_controller_reconciler_utils.go
> +				updatedConditions = append(updatedConditions, condition)
Right, currently we just replace the only condition so we wont break as of when this PR merges, however it could be a bit of a gotcha for future iterations if they add conditions not realizing the problem so taking care of it now more or less as a breadcrumb for future writers could be helpful, but I would also settle for a follow up issue where we remind ourselves to handle the problem in a forward-thinking manner.

2022-07-07 21:48 UTC, shaneutt commented on controllers/controlplane_controller_reconciler_utils.go
> +	envDontOverride map[string]struct{},
I think what we're actually looking for is the inverse: a global `alwaysOverride` map.

2022-07-07 22:01 UTC, jrsmroz commented on controllers/controlplane_controller_reconciler_utils.go
> +	envDontOverride map[string]struct{},
Sure, but that's other issue as you said :).

2022-07-07 22:02 UTC, jrsmroz commented on controllers/controlplane_controller_reconciler_utils.go
> +				updatedConditions = append(updatedConditions, condition)
Let's create follow up issue.

2022-07-07 23:54 UTC, shaneutt commented on controllers/controlplane_controller_reconciler_utils.go
> +	envDontOverride map[string]struct{},
Well no, we also want to follow the same logic here, this is pseudocode for the logic we want:

```golang
if isSpecial(var) {
    set(var, newValue)
} else {
   if isAlreadySet(var) {
       return fmt.Errorf("var already provided and not special can't override")
   } else {
       set(var, newValue)
   }
```

2022-07-08 08:06 UTC, jrsmroz commented on controllers/controlplane_controller_utils.go
> +func unsetEnv(envVars []corev1.EnvVar, name string) []corev1.EnvVar {
That's a good point, the function removes the var from the slice, but it does not have an effect of unsetting anything yet.

2022-07-08 08:11 UTC, jrsmroz commented on controllers/controlplane_controller_utils.go
> +func unsetEnv(envVars []corev1.EnvVar, name string) []corev1.EnvVar {
Wen with reject. drop is for removing 1st element.

2022-07-08 08:27 UTC, jrsmroz commented on controllers/controlplane_controller_reconciler_utils.go
> +				updatedConditions = append(updatedConditions, condition)
https://github.com/Kong/gateway-operator/issues/66

2022-07-08 15:20 UTC, mlavacca commented on controllers/controlplane_controller_utils.go
> +	if dataplaneIsSet {
Why not gather these two if blocks in a single one and get rid of the above shared boolean expression?

2022-07-08 15:20 UTC, mlavacca commented on controllers/controlplane_controller_utils.go
> +			spec.Env = updateEnv(spec.Env, "CONTROLLER_PUBLISH_SERVICE", controllerPublishService(*spec.DataPlane, namespace))
Since with this PR we are going to set these env vars dynamically with the change of the dataplaneName, I think we could get rid of this part here. What do you think?

2022-07-08 15:58 UTC, jrsmroz commented on controllers/controlplane_controller_utils.go
> +	if dataplaneIsSet {
Ohh, that is a mistake! it should be `if !dataplaneIsSet`

2022-07-08 16:12 UTC, jrsmroz commented on controllers/controlplane_controller_utils.go
> +	if dataplaneIsSet {
Yep. it's a leftover from time when there was envDontOverwrite map.

2022-07-08 17:01 UTC, jrsmroz commented on controllers/controlplane_controller_utils.go
> +			spec.Env = updateEnv(spec.Env, "CONTROLLER_PUBLISH_SERVICE", controllerPublishService(*spec.DataPlane, namespace))
I was thinking about that. But it saves a single create call during initial reconcile iteration. This will be refactored under https://github.com/Kong/gateway-operator/issues/65

2022-07-08 17:20 UTC, shaneutt approved these changes
Once other people's review comments are resolved, LGTM.

2022-07-08 19:29 UTC, pmalek approved these changes

2022-07-08 19:29 UTC, pmalek commented on controllers/controlplane_controller.go
> +	debug(log, "validating that the ControlPlane DataPlane configuration is up to date", controlplane)
```suggestion
	debug(log, "validating that the ControlPlane's DataPlane configuration is up to date", controlplane)
```

2022-07-08 19:29 UTC, pmalek commented on test/integration/controlplane_test.go
> +	require.Eventually(t, dataPlaneHasActiveDeployment(t, dataplaneName), time.Minute, time.Second)
nit: any particular reason that we wait here for 1 minute and in other places 2 minutes?

I was about to suggest to put that `waitTime` into a variable but then I've noticed the differences between the values. If there's no particular reason why those couldn't be equal I'd try to use a `const` for them

Similarly elsewhere.

2022-07-08 20:21 UTC, jrsmroz commented on test/integration/controlplane_test.go
> +	require.Eventually(t, dataPlaneHasActiveDeployment(t, dataplaneName), time.Minute, time.Second)
Mostly copy pasta and debug leftovers. 1 minute deadline should be enough everywhere. I will double checks the time before merging.

2022-07-08 20:35 UTC, jrsmroz commented
Heh, committing a suggestion removed the approvals. Did't expect that.

2022-07-08 21:02 UTC, jrsmroz commented on test/integration/controlplane_test.go
> +	require.Eventually(t, dataPlaneHasActiveDeployment(t, dataplaneName), time.Minute, time.Second)
unified those to 1 minute

2022-07-09 09:20 UTC, pmalek commented on test/integration/predicates_test.go
> +func controlPlaneIsScheduled(t *testing.T, controlplane types.NamespacedName) func() bool {
Nit about those predicates: I can see those being used at some point either by e2e or other suite of tests so I believe we might want to move it (not in this PR) to a separate package and exporting those so that they can be reused in other places.

2022-07-09 09:20 UTC, pmalek commented on controllers/controlplane_controller.go
> +				"conflict found when trying to ensure ControlPlane configuration was up to date, retrying",
```suggestion
				"conflict found when trying to ensure ControlPlane's DataPlane configuration was up to date, retrying",
```

2022-07-09 09:20 UTC, pmalek commented on controllers/controlplane_controller_reconciler_utils.go
> +func (r *ControlPlaneReconciler) ensureDataPlaneStatus(
This one either needs a comment or ... an argument? What I mean by that is that a name: `ensureDataPlaneStatus` asks for an argument, i.e. ensure status - what status?

2022-07-09 09:20 UTC, pmalek commented on controllers/controlplane_controller_utils.go
> +func envValue(env []corev1.EnvVar, name string) string {
```suggestion
func envValueByName(env []corev1.EnvVar, name string) string {
```

Perhaps this could help to make it obvious what this `func` does?

2022-07-09 09:20 UTC, pmalek commented on test/integration/controlplane_test.go
> +	require.Eventually(t, controlPlaneDetectedNoDataplane(t, controlplaneName), time.Minute, time.Second)
Now that most of these wait times are the same can we use a named `const` for those?

2022-07-09 18:45 UTC, jrsmroz commented on test/integration/predicates_test.go
> +func controlPlaneIsScheduled(t *testing.T, controlplane types.NamespacedName) func() bool {
Certainly not this in PR, it'd already quite big for what it does.

2022-07-10 08:32 UTC, pmalek commented on test/integration/predicates_test.go
> +func controlPlaneIsScheduled(t *testing.T, controlplane types.NamespacedName) func() bool {
Agreed 👍

2022-07-11 10:31 UTC, jrsmroz commented on test/integration/controlplane_test.go
> +	require.Eventually(t, controlPlaneDetectedNoDataplane(t, controlplaneName), time.Minute, time.Second)
Changed both, the deadline and tick to consts.

2022-07-11 10:46 UTC, pmalek commented on controllers/controlplane_controller_utils.go
> +func envValueByName(env []corev1.EnvVar, name string) string {
Can we add a comment on this to explain what it does? When is the empty string returned?

2022-07-11 10:46 UTC, pmalek commented on controllers/controlplane_controller_utils.go
> +func rejectEnv(envVars []corev1.EnvVar, name string) []corev1.EnvVar {
ditto here

2022-07-11 11:18 UTC, jrsmroz commented on controllers/controlplane_controller_utils.go
> +func envValueByName(env []corev1.EnvVar, name string) string {
done

2022-07-11 12:07 UTC, merged