RBAC and ServiceAccount management for ControlPlanes
Kong/gateway-operator pull request #58
Opened 2022-07-05 15:41 UTC by mlavacca

**What this PR does / why we need it**:
Automatic generation of ServiceAccount, ClusterRole, and ClusterRoleBinding for control-plane deployments.
What has been done:
* Creation of a `ClusterRole` generator in charge of creating `.go` files containing all the `rbac`-related code necessary to make the operator work.
* The controlplane controller now creates:
  * a `ServiceAccount` to be used by the controlplane deployment
  * a `ClusterRole` (automatically generated by the role-generator) to grant the permissions needed by the specific version of KIC
  * a `ClusterRoleBinding` to bind the role to the controlplane `ServiceAccount`
* The controlplane controller rbacs has been patched as follows:
  *  rbacs to create `ServiceAccounts`, `ClusterRole`, and `ClusterRoleBindings` have been added to `controllers/controlplane_controller_rbac.go`.
  * a set of files automatically generated by the role generator has been created under `controllers/versioned_clusterrole` containing the set of rbacs needed by each set of KIC versions. The operator needs those permission to correctly create the requested version of KIC.

**Which issue this PR fixes**
Fixes #28 

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect significant changes

2022-07-08 09:43 UTC, mlavacca commented
**For the reviewers**: I moved the generation functions into a new package under `internal/resources/kubernetes` and I created a new `.go` file for each type of resource. I followed this approach because the amount of resources that need to be created has increased, and having all of them in the controller's folder decrease the code readability. I would like to know if you think this re-organization suits well our needs, and, if so, I'll create an issue to move there also the other Kubernetes resources generation left untouched by this PR (services and deployments).

2022-07-08 09:59 UTC, mlavacca commented
A new follow-up related to this PR has been created: #67

2022-07-08 18:25 UTC, shaneutt requested changes

2022-07-08 18:25 UTC, shaneutt commented on config/samples/gateway.yaml
> +    namespace: default
What was the reason for adding an explicit namespace to the samples? :thinking:

2022-07-08 18:25 UTC, shaneutt commented on controllers/controlplane_controller.go
> +	debug(log, "looking for existing serviceAccounts for ControlPlane deployment", controlplane)
nit: while I'm sure we don't get this right _everywhere_ it's common to provide camel casing for API types that would match their `kind` even when referencing the type in a log, e.g.:

```suggestion
	debug(log, "looking for existing ServiceAccounts for ControlPlane Deployment", controlplane)
```

2022-07-08 18:25 UTC, shaneutt commented on controllers/controlplane_controller.go
> +		return ctrl.Result{Requeue: true, RequeueAfter: requeueWithoutBackoff}, nil // TODO: remove after https://github.com/Kong/gateway-operator/issues/26
We should update https://github.com/Kong/gateway-operator/issues/26 to include actions to take for these changes, OR we should add enqueue triggers so that changes to the related roles and bindings trigger reconcilation and subsequently recreate anything that's been deleted.

2022-07-08 18:25 UTC, shaneutt commented on controllers/controlplane_controller.go
> +	debug(log, "looking for existing clusterRoleBindings for ControlPlane deployment", controlplane)
```suggestion
	debug(log, "looking for existing ClusterRoleBindings for ControlPlane Deployment", controlplane)
```

2022-07-08 18:25 UTC, shaneutt commented on controllers/controlplane_controller.go
> +		return ctrl.Result{Requeue: true, RequeueAfter: requeueWithoutBackoff}, nil // TODO: remove after https://github.com/Kong/gateway-operator/issues/26
Same as above, update https://github.com/Kong/gateway-operator/issues/26 OR change the controller watch to trigger reconcilation when related roles and bindings are deleted.

2022-07-08 18:25 UTC, shaneutt commented on controllers/controlplane_controller_rbac.go
> +//+kubebuilder:rbac:groups=core,resources=events,verbs=create;patch
I'm suddenly glad I bothered to put this RBAC stuff into it's own file :hot_face: 

I think this is OK for now. The writing on the wall is that it's going to be tricky when RBAC stuff changes for the KIC. But this is a good enough place to start so let's start here and look for improvements iteratively.

2022-07-08 18:25 UTC, shaneutt commented on controllers/controlplane_controller_utils.go
> +					ServiceAccountName: serviceAccountName,
:+1:

2022-07-08 18:25 UTC, shaneutt commented on internal/resources/kubernetes/clusterrolebindings.go
> +package kubernetes
I'm noticing immediately that we've created `internal/resources/kubernetes` for these utilities when we do already have `internal/utils/kubernetes`. It seems to me we could put these in there for now to reduce sprawl, or did you have a strong preference and reason to separate this?

2022-07-08 18:25 UTC, shaneutt commented on internal/resources/kubernetes/clusterrolebindings.go
> +func GenerateNewClusterRoleBindingForControlPlane(namespace, controlplaneName, serviceAccountName, clusterRoleName string) *rbacv1.ClusterRoleBinding {
public symbol needs godoc comment

2022-07-08 18:25 UTC, shaneutt commented on internal/resources/kubernetes/clusterroles.go
> +func GenerateNewClusterRoleForControlPlane(controlplaneName string) *rbacv1.ClusterRole {
public symbol needs godoc comment

2022-07-08 18:25 UTC, shaneutt commented on internal/resources/kubernetes/clusterroles.go
> +		Rules: []rbacv1.PolicyRule{
This right here is a... a little tricky.

These hardcoded rules are effectively tied to the RBAC rules we provide the operator in `controllers/controlplane_controller_rbac.go`, though it requires a human developer to understand and know that and take action to update one list when the other updates.

This dichotomy is problematic: it could be error prone and lead to things like accidentally leaving in permissions that are not wanted when it was removed in one place but not the other.

It's a pain, I know, but I would suggest tying these things together, consider some of the options I thought up:

* generate this functionality from the RBAC generator flags
* add a test that proves the two separate permission sets have an appropriate union
* add code linting that verifies the permission set union

Consider these and let me know your thoughts?

2022-07-08 18:25 UTC, shaneutt commented on internal/resources/kubernetes/serviceaccounts.go
> +func GenerateNewServiceAccountForControlPlane(namespace, controlplaneName string) *corev1.ServiceAccount {
public symbol needs godoc comment

2022-07-11 16:46 UTC, mlavacca commented
I converted back the PR to draft to reduce noise and make clear I'm still working on it after Shane's comment.

2022-07-12 14:35 UTC, jrsmroz commented on controllers/controlplane_controller_reconciler_utils.go
> +) (bool, *corev1.ServiceAccount, error) {
Maybe name the returned values

2022-07-12 15:03 UTC, jrsmroz commented on internal/utils/kubernetes/resources/zz_generated_clusterrole_helpers.go
> +	}
What if image tag is `latest`? Will that work with the code below?

2022-07-12 15:28 UTC, mlavacca commented
Thank you for the review @jrsmroz, but this PR is still in draft, thus many comments would have been addressed once ready.

2022-07-12 15:36 UTC, jrsmroz commented
Sure.

2022-07-13 08:25 UTC, mlavacca commented on config/samples/gateway.yaml
> +    namespace: default
It was a workaround leftover for #76. I removed it.

2022-07-13 08:30 UTC, mlavacca commented on internal/resources/kubernetes/clusterrolebindings.go
> +package kubernetes
It was only a proposal for something I thought could have been a possible solution. Not a big deal anyway, I moved it under `internal/utils/kubernetes/resources`. Does it work for you?

2022-07-13 08:51 UTC, mlavacca commented on internal/resources/kubernetes/clusterroles.go
> +		Rules: []rbacv1.PolicyRule{
I thought a lot about your comment and totally agree with you. Furthermore, there were issues related to the version to use (KIC controller 2.4 needs a different set of permission from 2.1). I came up with a `ClusterRole` generator that fetches some specific versions from github and automatically generates this file and the `controller_rbac.go` one, for each explicitly set version. Below you can find a description of the mechanism.

https://github.com/Kong/gateway-operator/blob/e74736458f1ef9ba77a4ca2f040dc823b8a4f151/internal/versions/kicversions.go#L8-L30

Every time the KIC role is updated and released, we just need to add an entry in the map above and re-run the generator. New files will be automatically created. In this scenario, the operator will have all the permissions needed to create every version of KIC, but the ingress controller will have only the subset of permissions that it actually needs.

2022-07-13 08:54 UTC, mlavacca commented on internal/versions/kicversions.go
> +		"~2": consts.DefaultControlPlaneTag,
This map plays a key role in the generator; a detailed comment has been added.

2022-07-13 08:54 UTC, mlavacca commented on internal/utils/kubernetes/resources/zz_generated_clusterrole_helpers.go
> +	}
now it fetches the latest available version of the role

2022-07-13 08:55 UTC, mlavacca commented on hack/generators/kic-role-generator/main.go
> +func match(path string, buffer []byte) (bool, error) {
the function name has been changed and a comment has been added

2022-07-13 08:56 UTC, mlavacca commented on hack/generators/kic-role-generator/main.go
> +	}
split in two function calls

2022-07-13 09:03 UTC, mlavacca commented on controllers/controlplane_controller_rbac.go
> +//+kubebuilder:rbac:groups=core,resources=events,verbs=create;patch
This huge file has been split as follows:
* only the permission to create `ServiceAccounts` and `rbacs` has been added to the old  `controllers/controlplane_controller_rbac.go`
* all the other permissions needed by KIC have been created in `controllers/versioned_clusterroles`. Each `*_rbac.go` file contains the `rbacs` needed by a specific range of kIC versions.

2022-07-13 09:07 UTC, mlavacca commented on controllers/controlplane_controller.go
> +		return ctrl.Result{Requeue: true, RequeueAfter: requeueWithoutBackoff}, nil // TODO: remove after https://github.com/Kong/gateway-operator/issues/26
I updated the issue

2022-07-14 14:47 UTC, shaneutt approved these changes
Looking good, great place to start. I really like your approach with version awareness it helps to solve a couple of sub-problems. Only some minor comments to resolve and then LGTM.

2022-07-14 14:47 UTC, shaneutt commented on controllers/controlplane_controller.go
> +	debug(log, "looking for existing ServiceAccounts for ControlPlane deployment", controlplane)
```suggestion
	debug(log, "ensuring ServiceAccount for ControlPlane deployment exists", controlplane)
```

2022-07-14 14:47 UTC, shaneutt commented on controllers/controlplane_controller.go
> +	debug(log, "looking for existing ClusterRoles for ControlPlane deployment", controlplane)
```suggestion
	debug(log, "ensuring ClusterRoles for ControlPlane deployment exist", controlplane)
```

2022-07-14 14:47 UTC, shaneutt commented on controllers/controlplane_controller.go
> +	debug(log, "looking for existing ClusterRoleBindings for ControlPlane Deployment", controlplane)
```suggestion
	debug(log, "ensuring that ClusterRoleBindings for ControlPlane Deployment exist", controlplane)
```

2022-07-14 14:47 UTC, shaneutt commented on hack/generators/kic-role-generator/templates.go
> +// TemplateData is the struct with data to be used to properly render
```suggestion
// templateData is the struct with data to be used to properly render
```

2022-07-14 14:47 UTC, shaneutt commented on internal/versions/kicversions.go
> +		">=2.4":      "2.5",
We need to add a TODO here and create a follow up issue: in the future we need to know what our actual version limits are because we currently can't actually know that we'll be compatible with say, 2.6 which has not released yet. Not something we need to solve now, but something we should have some kind of solution for before our first alpha release.

2022-07-14 14:47 UTC, shaneutt commented on internal/versions/kicversions.go
> +		// TODO: Add older versions of KIC
At this point, we DONT want older versions of the KIC to be supported. It's possible our first GA release of this operator would be 3.0+ only. Just something to keep in mind, feel free to delete this line for now because we don't want to mess with v1 releases.

2022-07-14 14:53 UTC, shaneutt commented on internal/resources/kubernetes/clusterroles.go
> +		Rules: []rbacv1.PolicyRule{
I like this approach, great place to get started :+1:

2022-07-15 09:04 UTC, mlavacca commented on internal/versions/kicversions.go
> +		">=2.4":      "2.5",
https://github.com/Kong/gateway-operator/issues/86

2022-07-15 14:59 UTC, shaneutt requested changes
The test looks good thanks for adding it. Just one final comment and then I think we're good to go :+1:

2022-07-15 14:59 UTC, shaneutt commented on internal/versions/kicversions.go
> +		">=2.4":      "2.5", // TODO: https://github.com/Kong/gateway-operator/issues/86
:+1:

2022-07-15 14:59 UTC, shaneutt commented on test/integration/ingress_test.go
> +	ingress := generators.NewIngressForServiceWithClusterVersion(kubernetesVersion, "/httpbin", map[string]string{
the `/httpbin` path is commonly used and so it might be easy for other tests to eventually collide with it, causing false positives in this test.

As such I would use a unique path instead, you might consider using the test name:

```suggestion
	ingress := generators.NewIngressForServiceWithClusterVersion(kubernetesVersion, fmt.Sprintf("/%s-httpbin", strings.ToLower(t.Name())), map[string]string{
```

Or maybe even just generate the path entirely:

```suggestion
	httpbinPath := uuid.NewString()
	ingress := generators.NewIngressForServiceWithClusterVersion(kubernetesVersion, httpbinPath, map[string]string{
```

2022-07-15 16:22 UTC, shaneutt approved these changes

2022-07-15 16:25 UTC, merged

2022-07-16 12:06 UTC, jrsmroz commented on hack/generators/kic-role-generator/helpers.go
> +	constraint = strings.ReplaceAll(constraint, "=", "eq")
I know this was already merged, but this could be done by a replacer instead multiple calls to `ReplaceAll`\
https://pkg.go.dev/strings#Replacer