Conditions as a snapshot
Kong/gateway-operator pull request #78
Opened 2022-07-13 12:22 UTC by ruromero

Signed-off-by: ruromero <rromerom@redhat.com>

**What this PR does / why we need it**:

Following up the discussion on the linked issue and the slack channel. I suggest the Conditions to be used as a snapshot of the current state so that it is easier to understand and monitor the current state of all the managed resources.

This is the current list of Conditions considered in the Gateway Status.

* Scheduled: existing condition describing that the operator will process the gateway
* DataPlaneReady: If the dataplane resource is ready
* ControlPlaneReady: If the controlPlane resource is ready
* GatewayService: whether the Gateway service is properly configured. At the moment if the ip is empty (as it is in my case) it will show a descriptive error instead of an error trace.
* Ready: overall ready condition that aggregates the other conditions

Example: 

```
- lastTransitionTime: "2022-07-13T12:12:58Z"
  message: this gateway has been picked up by the konghq.com/gateway-operator and will be processed
  reason: Scheduled
  status: "True"
  type: Scheduled
- lastTransitionTime: "2022-07-13T12:12:58Z"
  message: ""
  reason: ResourceReady
  status: "True"
  type: DataPlaneReady
- lastTransitionTime: "2022-07-13T12:12:58Z"
  message: ""
  reason: ResourceReady
  status: "True"
  type: ControlPlaneReady
- lastTransitionTime: "2022-07-13T12:12:58Z"
  message: missing loadbalancer.ingress[0].ip
  reason: GatewayServiceError
  status: "False"
  type: GatewayService
- lastTransitionTime: "2022-07-13T12:12:58Z"
  message: ""
  reason: DependenciesNotReady
  status: "False"
  type: Ready
```

**Which issue this PR fixes**

Fix https://github.com/Kong/gateway-operator/issues/66

**Special notes for your reviewer**:

Let me know if you require a higher level of code coverage at this point

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect significant changes

2022-07-13 16:14 UTC, jrsmroz commented
It seems `ensureDataPlaneStatus` uses the old way to update the status.

2022-07-13 16:51 UTC, jrsmroz reviewed
Thanks for submitting that. I like the idea. I've went through and noticed some places that raised my concerns.

2022-07-13 16:51 UTC, jrsmroz commented on controllers/controlplane_controller_reconciler_utils.go
> +		}
Shouldn't that be replaced by `CreateCondition` call?

2022-07-13 16:51 UTC, jrsmroz commented on controllers/controlplane_controller_reconciler_utils.go
> +		LastTransitionTime: metav1.Now(),
`CreateCondition`

2022-07-13 16:51 UTC, jrsmroz commented on controllers/dataplane_controller_reconciler_utils.go
> +		k8sutils.SetCondition(condition, dataplane)
`CreateCondition`

2022-07-13 16:51 UTC, jrsmroz commented on controllers/dataplane_controller_reconciler_utils.go
> +		LastTransitionTime: metav1.Now(),
`CreateCondition `

2022-07-13 16:51 UTC, jrsmroz commented on controllers/gateway_controller_conditions.go
> +type GatewayConditionType string
I guess we need same for data plane and control plane controllers?

2022-07-13 16:51 UTC, jrsmroz commented on controllers/gateway_controller_conditions.go
> +}
I'm ok with usage of decorator, but I would go with less generic name. That generator purpose seems to be implementing `ConditionsAware`.

2022-07-13 20:09 UTC, shaneutt requested changes
Looking good, thank you for your contribution :bow: 

A few minor comments.

2022-07-13 20:09 UTC, shaneutt commented on controllers/gateway_controller_conditions.go
> +
```suggestion
```

2022-07-13 20:09 UTC, shaneutt commented on controllers/gateway_controller_conditions.go
> +type GatewayDecorator struct {
Does this type need to be public? And in either case it would seem helpful if we could document it with a godoc comment.

2022-07-13 20:09 UTC, shaneutt commented on internal/utils/kubernetes/status.go
> +
```suggestion
```

2022-07-13 23:25 UTC, jrsmroz commented on controllers/controlplane_controller_reconciler_utils.go
> +		LastTransitionTime: metav1.Now(),
I'm saying it should be `k8sutils.CreateCondition` call instead of creating struct by hand.

2022-07-14 07:57 UTC, ruromero commented on controllers/gateway_controller_conditions.go
> +}
I think this is not the only interface the decorator will be implementing. I like the name of the pattern it is implementing instead of naming it something like `GatewayWithConditions` or similar, but you're the gatekeepers, you have the final word :smile:

2022-07-14 07:58 UTC, ruromero commented on controllers/gateway_controller.go
> +	return ctrl.Result{}, r.Client.Status().Update(ctx, gateway.Gateway)
Uhm, this is how it was before IIRC but I'm fine with making it conditional

2022-07-14 13:28 UTC, shaneutt commented on controllers/gateway_controller.go
> +	return ctrl.Result{}, r.Client.Status().Update(ctx, gateway.Gateway)
Well at least not in `main`. Currently in main once we log this entry there's no other reconciliation logic performed thereafter:

https://github.com/Kong/gateway-operator/blob/a817f1f1a67a105fb6dc20e8f3e4439298958fbd/controllers/gateway_controller.go#L222

2022-07-14 14:10 UTC, ruromero commented
I am adding another convenience method to update only the state when necessary

2022-07-14 19:07 UTC, shaneutt commented on controllers/gateway_controller_conditions.go
> +}
I agree with Jarek that `Decorator` is very generic. I actually don't think `GatewayWithConditions` is really all that bad, but as you suggest that this will be adding more implementations than just conditions so maybe not.

Since this comment was originally made the type has been given godocs to signal its intention, and it's been made private. So at this point it's easy to refactor since it's not part of any public API I think we can keep the name as-is for the moment.

2022-07-15 13:28 UTC, ruromero commented on controllers/gateway_controller_conditions.go
> +type GatewayDecorator struct {
I made it private

2022-07-15 13:28 UTC, ruromero commented
@shaneutt updated and rebased

2022-07-15 15:38 UTC, shaneutt submitted a review, later dismissed
There are a couple of failing lints and a type issue in the integration tests to clean up but other than that it's looking good. Once @jrsmroz is :heavy_check_mark: I'm :heavy_check_mark: for merging this. I think there's possibly some room for further tweaks but the fundamentals and tests are there and we're in an early development stage so a lot of this will undergo refactor before our first alpha release so we don't want to spend too many cycles off the critical path anyhow.

Thank you so much for your contribution!

2022-07-18 15:55 UTC, jrsmroz commented on controllers/controlplane_controller_reconciler_utils.go
> +	return false
nitpick: So this function is names `isMarkedScheduled`, but it has a sideffect, it modifies the control-plane conditions. That may be misleasing.

2022-07-21 06:15 UTC, ruromero commented on controllers/controlplane_controller_reconciler_utils.go
> +	return false
You're totally right, renaming back

2022-07-21 06:25 UTC, ruromero commented
Updated PR. Let me know once it's OK and I'll do the squash

2022-07-21 14:31 UTC, shaneutt submitted a review, later dismissed

2022-07-21 14:47 UTC, ruromero commented
I'm going through the integration tests

2022-07-22 17:09 UTC, shaneutt approved these changes
I think the fundamentals here are solid. Since we're still pre-alpha we have the freedom to take a fix-it-forward attitude for any other changes we could have still suggested, so I'm in favor of that approach so as to not increase the size and burden of handling more in this single PR.

This is great, thanks for all the hard work on this @ruromero :vulcan_salute:

2022-07-22 17:14 UTC, shaneutt commented on controllers/dataplane_controller_reconciler_utils.go
> +		LastTransitionTime: metav1.Now(),
To avoid having to hold up this PR any longer, I've created a follow up for this: https://github.com/Kong/gateway-operator/issues/101

2022-07-22 17:14 UTC, merged

2022-07-22 19:28 UTC, jrsmroz commented
Thanks