fix: namespace checked before being dereferenced
Kong/gateway-operator pull request #79
Opened 2022-07-13 13:24 UTC by mlavacca

**What this PR does / why we need it**:
`gatewayClass.Spec.ParametersRef.Namespace` checked before being dereferenced.

**Which issue this PR fixes**
Fixes #76 

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect significant changes

2022-07-13 14:10 UTC, shaneutt requested changes

2022-07-13 14:10 UTC, shaneutt commented on controllers/gateway_controller_reconciler_utils.go
> +	if gatewayClass.Spec.ParametersRef.Namespace != nil {
For thorough-ness we should check if `ParametersRef` is `nil`:

```suggestion
	if gatewayClass.Spec.ParametersRef != nil && gatewayClass.Spec.ParametersRef.Namespace != nil {
```

2022-07-13 14:23 UTC, shaneutt commented on controllers/gateway_controller_reconciler_utils.go
> +	if gatewayClass.Spec.ParametersRef.Namespace != nil {
I see :thinking: 

So functionally that works for our current purposes but it means that the functionality of `getGatewayConfigForGatewayClass` doesn't have this problem solved in encapsulation (that is to say, by itself in a vacuum) so if other callers were to start calling this method it may not be clear to them that this problem exists, and that could create some potential for bugs for any new callers down the road that wouldn't be abundantly clear to the caller unless they carefully studied other calling code.

Generally we shouldn't have to study the calling code for a function or method to understand how to use it properly: we should aim for the function signature and godoc definition to give us as much as possible and for these kinds of problems to be solved internally so I would still advocate that we make this change here for completeness of the method.

2022-07-13 14:33 UTC, mlavacca commented on controllers/gateway_controller_reconciler_utils.go
> +	if gatewayClass.Spec.ParametersRef.Namespace != nil {
I get it, I'll add the check also here.

2022-07-13 15:35 UTC, pmalek approved these changes

2022-07-13 16:30 UTC, pmalek submitted a review, later dismissed

2022-07-13 17:00 UTC, jrsmroz commented
@shaneutt  Can we still proceed when it's nil/empty?

2022-07-13 19:00 UTC, shaneutt requested changes

2022-07-13 19:00 UTC, shaneutt commented on controllers/gateway_controller_reconciler_utils.go
> +	}
So on second glance, and after thinking about @jrsmroz's comment it seems kinda weird to try the GET if we don't have a namespace, since `GatewayClass` is cluster scoped so there's no _inherent_ namespace and choosing the default namespace of the kubeconfig also feels kinda wrong.

It seems what we should actually be doing is moving the code from the caller that makes a new empty/default config into this method. That will remove the need for the wrapping method and solve this dilemma. Sorry I didn't think of this on my previous review.

2022-07-13 23:48 UTC, jrsmroz commented
Can we not use auto merge option? Please 🙏. It's better to do a detailed review instead of pushing on first accept.

2022-07-14 13:22 UTC, shaneutt requested changes
So the current code looks good, but it appears we need to add something to the calling code to handle this situation: the currently existing calling code should be able to tolerate the error and simply provide an empty configuration, similar to what it's already doing, since not having a parametersref is not a fatal condition for Gateway reconcilation.

I recommend we create a distinct error in `/pkg/errors`, perhaps something like:

```golang
var ErrObjectMissingReferences = "object has not reference to related objects"
```

Not necessarily 100% sold on the above one, so just consider that an example, but the point being the calling code could do:

```golang
if errors.Is(err, ErrObjectMissingReferences) {
    return NewGatewayConfiguration()
}
```

Let me know your thoughts? :thinking:

2022-07-14 14:10 UTC, jrsmroz commented
> > Can we not use auto merge option? Please pray. It's better to do a detailed review by more than one reviewer instead of pushing on first accept.
> > I'm not saying to wait for 2 approvals, but just give people chance to read the code.
> 
> This is probably something we should bring up in retro and discuss making changes to, as the opposite of what you're suggesting has been the standard on the team for a long time.

Sure, I will bring that up. Not sure if auto merges going to scale with bigger team.

2022-07-14 15:00 UTC, shaneutt commented
> > > Can we not use auto merge option? Please pray. It's better to do a detailed review by more than one reviewer instead of pushing on first accept.
> > > I'm not saying to wait for 2 approvals, but just give people chance to read the code.
> > 
> > 
> > This is probably something we should bring up in retro and discuss making changes to, as the opposite of what you're suggesting has been the standard on the team for a long time.
> 
> Sure, I will bring that up. Not sure if auto merges going to scale with bigger team.

Yeah, it really might not. We just need to talk about this and find some consensus.

2022-07-15 09:51 UTC, mlavacca commented
> the currently existing calling code should be able to tolerate the error and simply provide an empty configuration, similar to what it's already doing, since not having a parametersref is not a fatal condition for Gateway reconciliation.

A new error has been added, and the parametersRef field is checked only inside `getGatewayConfigForGatewayClass`. when not set, an error of type `ObjectMissingParametersRefError` Is returned and caught by the caller, which creates an empty instance of the configuration (as it was already before).

2022-07-15 14:14 UTC, shaneutt requested changes
I have a couple of small comments and then I think we're ready to go.

On a side note, I noticed a couple things about this area of code:

1. I don't see strong value in having wrapper functions like `IsObjectMissingParametersRef` over just calling `errors.Is(err, ObjectMissingParametersRefError)`. If we continue this trend we'll add 4+ lines for every error we add to minimally change the semantics of a one line check and I'm just not convinced of the value.
2. I noticed we're using `<Name>Error` in these files, but in our public `pkg/errors/` package we use `Err<Name>`. We should be consistent about how we name our errors.

Neither of these problems originates from this PR so I leave it up to you, if you feel inclined to do refactoring then I would ask that we change these things. If you don't and you wouldn't mind putting in a small follow up issue then that's fine too.

2022-07-15 14:14 UTC, shaneutt commented on internal/errors/errors.go
> +func NewObjectMissingParametersRef(obj metav1.Object) error {
public symbols should have `godoc` comments

2022-07-15 14:14 UTC, shaneutt commented on internal/errors/errors.go
> +func IsObjectMissingParametersRef(err error) bool {
public symbols should have `godoc` comments

2022-07-15 14:14 UTC, shaneutt commented on internal/errors/errors.go
> +	return errors.As(err, &onwRefErr)
I just noticed that we're using `errors.As` here as was done above previously. `errors.As` makes modifications to the second operand that don't seem to have any bearing here, so even though this PR didn't start this we should take the time to switch to `errors.Is` here and nearby.

2022-07-15 14:57 UTC, mlavacca commented on internal/errors/errors.go
> +	return errors.As(err, &onwRefErr)
As far as I know (and I tried as a double check) `errors.As` is the way to handle custom errors that implement the error interface. If we replace it with `errors.Is`, the condition returns always false. `errors.Is` matches only simpler errors created by `errors.New`, and not custom errors, which require `errors.As`.

2022-07-15 15:06 UTC, shaneutt commented on internal/errors/errors.go
> +	return errors.As(err, &onwRefErr)
Well it wouldn't be the first time that I was confused :joy: 

But consider the following program:

```golang
package main

import (
	"errors"
	"fmt"
)

type ErrA struct{}

func (e ErrA) Error() string {
	return "error a"
}

type ErrB struct{}

func (e ErrB) Error() string {
	return "error b"
}

func main() {
	errA := ErrA{}
	errB := ErrB{}
	fmt.Printf("Is a == a? %t\n", errors.Is(errA, ErrA{}))
	fmt.Printf("Is b == b? %t\n", errors.Is(errB, ErrB{}))
	fmt.Printf("Is a == b? %t\n", errors.Is(errA, ErrB{}))
	fmt.Printf("Is b == a? %t\n", errors.Is(errB, ErrA{}))
}
```

It returns this output:

```console
$ go run main.go
Is a == a? true
Is b == b? true
Is a == b? false
Is b == a? false
```

Am I missing something :thinking:

2022-07-15 15:08 UTC, shaneutt commented on internal/errors/errors.go
> +	return errors.As(err, &onwRefErr)
Well it wouldn't be the first time that I was confused :joy: 

But consider the following program:

```golang
package main

import (
	"errors"
	"fmt"
)

type ErrA struct{}

func (e ErrA) Error() string {
	return "error a"
}

type ErrB struct{}

func (e ErrB) Error() string {
	return "error b"
}

func main() {
	errA := ErrA{}
	errB := ErrB{}
	fmt.Printf("Is a == a? %t\n", errors.Is(errA, ErrA{}))
	fmt.Printf("Is b == b? %t\n", errors.Is(errB, ErrB{}))
	fmt.Printf("Is a == b? %t\n", errors.Is(errA, ErrB{}))
	fmt.Printf("Is b == a? %t\n", errors.Is(errB, ErrA{}))
}
```

It returns this output:

```console
$ go run main.go
Is a == a? true
Is b == b? true
Is a == b? false
Is b == a? false
```

Am I missing something :thinking:

2022-07-15 15:09 UTC, shaneutt commented on internal/errors/errors.go
> +	return errors.As(err, &onwRefErr)
Well it wouldn't be the first time that I was confused :joy: 

But consider the following program:

```golang
package main

import (
	"errors"
	"fmt"
)

type ErrA struct{}

func (e ErrA) Error() string {
	return "error a"
}

func NewErrA() error {
	return ErrA{}
}

type ErrB struct{}

func (e ErrB) Error() string {
	return "error b"
}

func NewErrB() error {
	return ErrB{}
}

func main() {
	errA := NewErrA()
	errB := NewErrB()
	fmt.Printf("Is a == a? %t\n", errors.Is(errA, ErrA{}))
	fmt.Printf("Is b == b? %t\n", errors.Is(errB, ErrB{}))
	fmt.Printf("Is a == b? %t\n", errors.Is(errA, ErrB{}))
	fmt.Printf("Is b == a? %t\n", errors.Is(errB, ErrA{}))
}
```

It returns this output:

```console
$ go run main.go
Is a == a? true
Is b == b? true
Is a == b? false
Is b == a? false
```

Am I missing something :thinking:

2022-07-15 15:12 UTC, mlavacca commented
> I don't see strong value in having wrapper functions like IsObjectMissingParametersRef over just calling errors.Is(err, ObjectMissingParametersRefError). If we continue this trend we'll add 4+ lines for every error we add to minimally change the semantics of a one line check and I'm just not convinced of the value.

I see the value of those wrappers in having a one-liner that includes these two instructions
```go
var onwRefErr *ObjectMissingParametersRefError
if errors.As(err, &onwRefErr) {
    ...
}
```
for each error check. My opinion is that we can get rid of them, but the code readability will decrease.

> I noticed we're using <Name>Error in these files, but in our public pkg/errors/ package we use Err<Name>. We should be consistent about how we name our errors.

What do you think if we gather all the errors under the same package and we make uniform the naming? When I created this package under internal I didn't notice that there was already one under `pkg`. Would you use `pkg` or `internal`? I personally prefer `pkg` at this point.

2022-07-15 15:17 UTC, shaneutt commented
> > I don't see strong value in having wrapper functions like IsObjectMissingParametersRef over just calling errors.Is(err, ObjectMissingParametersRefError). If we continue this trend we'll add 4+ lines for every error we add to minimally change the semantics of a one line check and I'm just not convinced of the value.
> 
> I see the value of those wrappers in having a one-liner that includes these two instructions
> 
> ```go
> var onwRefErr *ObjectMissingParametersRefError
> if errors.As(err, &onwRefErr) {
>     ...
> }
> ```
> 
> for each error check. My opinion is that we can get rid of them, but the code readability will decrease.

Ok, so this hinges on the `errors.Is` vs `errors.As` thing. If we find that I'm wrong about `errors.Is` then we can leave this be. If I'm right though, I think we should remove these because then it's a 1:1 for lines.
 
> > I noticed we're using Error in these files, but in our public pkg/errors/ package we use Err. We should be consistent about how we name our errors.
> 
> What do you think if we gather all the errors under the same package and we make uniform the naming? When I created this package under internal I didn't notice that there was already one under `pkg`. Would you use `pkg` or `internal`? I personally prefer `pkg` at this point.

Sure let's combine them. I would advise moving everything under `internal/errors` for now because it's easy to move things to public later but the opposite is slightly less true and becomes even less true as releases happen. I would also advocate for the `Err<Name>` convention, as this is helpful for autocomplete tooling to hone in on those symbols in a lexicographical manner.

2022-07-15 15:47 UTC, mlavacca commented on internal/errors/errors.go
> +	return errors.As(err, &onwRefErr)
Look like the difference is when you have fields in the struct:
```go
package main

import (
	"errors"
	"fmt"
)

type ErrA struct {
	message string
	number  int
}

func (e ErrA) Error() string {
	return fmt.Sprintf("error %s, number %d", e.message, e.number)
}

func NewErrA(message string, number int) error {
	return &ErrA{
		message: message,
		number:  number,
	}
}

type ErrB struct {
	message string
	number  int
}

func (e ErrB) Error() string {
	return "error b"
}

func NewErrB(message string, number int) error {
	return ErrB{
		message: message,
		number:  number,
	}
}

func main() {
	fmt.Println("errors.Is")
	errA := NewErrA("testA", 123)
	errB := NewErrB("testB", 456)
	fmt.Printf("Is a == a? %t\n", errors.Is(errA, ErrA{}))
	fmt.Printf("Is b == b? %t\n", errors.Is(errB, ErrB{}))
	fmt.Printf("Is a == b? %t\n", errors.Is(errA, ErrB{}))
	fmt.Printf("Is b == a? %t\n", errors.Is(errB, &ErrA{}))

	fmt.Println("errors.As")
	var errACheck *ErrA
	var errBCheck *ErrB
	fmt.Printf("Is a == a? %t\n", errors.As(errA, &errACheck))
	fmt.Printf("Is b == b? %t\n", errors.As(errB, &errBCheck))
}
```

It return the output:
```sh
errors.Is
Is a == a? false
Is b == b? false
Is a == b? false
Is b == a? false
errors.As
Is a == a? true
Is b == b? false
```

In that case, to match the error you have to return a pointer to the error, and check it with `errors.As` (as far as I'm getting 😆 )

2022-07-18 14:28 UTC, shaneutt approved these changes
Once @jrsmroz's is :+1: I'm :+1:

2022-07-21 08:18 UTC, jrsmroz commented on internal/errors/gatewayclass.go
> +type ErrObjectMissingParametersRef struct {
That is not proper name. ErrXXX is for vars. For a type it should be `ObjectMissingParametersRerError`

2022-07-21 08:31 UTC, jrsmroz commented
> 2\. I noticed we're using `<Name>Error` in these files, but in our public `pkg/errors/` package we use `Err<Name>`. We should be consistent about how we name our errors.

- `<Name>Error` is for types
- `Err<Name>` is for vars.

2022-07-21 08:39 UTC, jrsmroz commented
> * I don't see strong value in having wrapper functions like `IsObjectMissingParametersRef` over just calling `errors.Is(err, ObjectMissingParametersRefError)`. If we continue this trend we'll add 4+ lines for every error we add to minimally change the semantics of a one line check and I'm just not convinced of the value.

I fully agree. We willbloat our error package for no good reason. I believe we should define our errors as vars, i.e
```go
var ErrDataPlaneNotSet = errors.New("no dataplane name set on controlplane")
```

Then if one wants to add more context info to that, just use:
```go
return fmt.Errorf("%w, controlplane = %s/%s", operatorerrors.ErrDataPlaneNotSet, obj.GetNamespace(), obj.GetName())
```

2022-07-21 08:40 UTC, jrsmroz commented on internal/errors/controlplane.go
> +		message: fmt.Sprintf("no dataplane name set on controlplan %s/%s spec", obj.GetNamespace(), obj.GetName()),
A type, should be `controlplane`, not `controlplan`

2022-07-21 09:51 UTC, jrsmroz requested changes
Please address the review comments regarding error handling.

2022-07-21 09:54 UTC, jrsmroz commented on internal/errors/controlplane.go
> +	object  metav1.Object
We don't use that addition information. And I doubt we will have a use for it.

2022-07-21 14:00 UTC, jrsmroz commented on controllers/gateway_controller_reconciler_utils.go
> +		return nil, fmt.Errorf("GatewayClass %s has invalid ParametersRef: both namespace and name must be provided", gatewayClass.Name)
Frankly, this can be `operatorerrors.ErrObjectInvalidParametersRef`.

2022-07-21 14:02 UTC, jrsmroz approved these changes
LGTM. I've added one more comment, but no need to address that right now. `DataPlaneNotSetError` should be changed too, but again, not in this PR.

2022-07-21 14:05 UTC, mlavacca commented on controllers/gateway_controller_reconciler_utils.go
> +		return nil, fmt.Errorf("GatewayClass %s has invalid ParametersRef: both namespace and name must be provided", gatewayClass.Name)
Yes, it may be, but I don't see the point in having it. In this case, we should requeue with error, as we do.

2022-07-21 14:07 UTC, mlavacca commented
> LGTM. I've added one more comment, but no need to address that right now. `DataPlaneNotSetError` should be changed too, but again, not in this PR.

? what's wrong with `ErrDataPlaneNotSet` now?

2022-07-21 15:07 UTC, jrsmroz commented
> > LGTM. I've added one more comment, but no need to address that right now. `DataPlaneNotSetError` should be changed too, but again, not in this PR.
> 
> ? what's wrong with `ErrDataPlaneNotSet` now?

My bad. i didn't notice you changed that too.

2022-07-21 15:09 UTC, jrsmroz commented on controllers/gateway_controller_reconciler_utils.go
> +		return nil, fmt.Errorf("GatewayClass %s has invalid ParametersRef: both namespace and name must be provided", gatewayClass.Name)
Yep, we can skip that now

2022-07-21 15:28 UTC, merged