feat: dataplace subresources replacement
Kong/gateway-operator pull request #91
Opened 2022-07-18 16:34 UTC by mlavacca

**What this PR does / why we need it**:

**Which issue this PR fixes**
Fixes #26 

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect significant changes

2022-07-21 13:18 UTC, pmalek reviewed
I'll do a more detailed review later on (if none of the team members do it faster) but I'd like to point to 3 things:

- Don't we need a CHANGELOG entry for this PR?
- That PR has a pretty empty description: can we add something to it?
- It links to an issue (with lots of sub tasks). Does it solve all of these? There are all already marked as done 🤔

2022-07-21 14:09 UTC, mlavacca commented on controllers/controlplane_controller_reconciler_utils.go
> +			client.MatchingLabels{consts.GatewayOperatorControlledLabel: consts.ControlPlaneManagedLabelValue},
Yep I agree, I'll add some comments

2022-07-21 14:09 UTC, mlavacca commented on controllers/controlplane_controller_watch.go
> +			fmt.Errorf("unexpected object type provided"),
good point, I'll do it

2022-07-21 14:29 UTC, pmalek commented on controllers/controlplane_controller_watch.go
> +		log.FromContext(context.Background()).Error(
Perhaps there's no other way to initialize the logger (as far as I can see in https://pkg.go.dev/sigs.k8s.io/controller-runtime@v0.12.3/pkg/log) 🤔 ?

In such case I'd postpone changing this till a subsequent PR where the `context.Context` is passed down form the call site. The (possibly) network calls like `r.Client.List()` in this file will also benefit from it.

2022-07-21 17:43 UTC, shaneutt commented on controllers/controlplane_controller_watch.go
> +		log.FromContext(context.Background()).Error(
> was any specific reason behind having log.FromContext(context.Background()) in the predicates and mapping functions?

The conditions where we would actually log these lines are effectively _programmer error_ type conditions, because they have to do with the wrong type being set. These log lines are there for completeness and ultimately to handle the situation where there was a bug so it could be caught without having to crash the watcher.

> Perhaps there's no other way to initialize the logger

At least at the time of writing I don't think I saw any other way, though you're welcome to dig around. So in theory it's asking us to provide a context but this mapper happens within the [linguistic, not Go] context of the controller-runtime machinery so `context.Background()` is probably reasonably accurate unless you have some additional constraints like a timeout you feel need to be set on it (which I don't think I see any reason to do so).

> In such case I'd postpone changing this till a subsequent PR where the context.Context is passed down form the call site. The (possibly) network calls like r.Client.List() in this file will also benefit from it.

We could advocate for this upstream in `controller-runtime`, arguing that these mapper and predicate functions might need to making blocking calls but I do imagine any traction on such a change would be pretty slow to pick up.

2022-07-22 08:19 UTC, pmalek commented on controllers/controlplane_controller_watch.go
> +		log.FromContext(context.Background()).Error(
👍 I do think that bringing this upstream might be very long and slow journey.

In that case I'd just propose to create an issue to introduce `context.Context` arguments around here so that these can be passed around and used in the logger creation and in k8s API requests.

2022-07-22 14:10 UTC, shaneutt commented
Given that we don't have the first release yet, I think it's OK for us to build the changelog entry for `v0.1.0` at the end of all other issues, wherein we just list the high level deliverables provided there. Then after that point we should be treating the changelog normally.

2022-07-22 15:18 UTC, mlavacca commented on controllers/controlplane_controller_watch.go
> +		log.FromContext(context.Background()).Error(
I took a look at how we do in KIC, and the main difference is that we set and initialize a log in the reconciler struct instance at `SetupWithManager` time in all the controllers. That logger is used anytime we need it (also in the predicates and mapping functions). I think we could follow that approach and have a more structured way to access the logger, but I think that's also out of scope for this PR to refactor our logging structure.

If you agree we can follow the same approach we have in KIC, I'll create an issue to track this.

2022-07-22 17:06 UTC, shaneutt requested changes
My main takeaways here are concerns about our replacement over reduction strategy for dealing with extra sub-resources. In some cases (some of which are edge, some maybe less so) this could cause significant disruption and even outage I think so let's take a good long look at these and see if we can remove those potential disruptions.

2022-07-22 17:06 UTC, shaneutt commented on controllers/dataplane_controller_reconciler_utils.go
> +		if err := r.Client.DeleteAllOf(ctx, &appsv1.Deployment{},
Now this replacement over reduction is particularly disruptive, this means if we ever get into a position where we have more than one `DataPlane` running, we stomp all of them, stopping traffic from flowing until the replacement comes online. Similar to my above comments about reducing rather than replacing, we should also do what `ReplicaSets` do with `Pods` and make sure the changing is gradual. For instance, if we decide that we have 1 `DataPlane` that's up and running that needs to be deleted, we don't delete it until we have a replacement `DataPlane` which is in the same state.

For the `DataPlane` version of this, I'm a bit more hesitant to say we can do this in a separate iteration, there's a lot more room for problems here because while the `ControlPlane` operates on eventual consistency terms, the `DataPlane` is realtime.

2022-07-22 17:06 UTC, shaneutt commented on controllers/dataplane_controller_reconciler_utils.go
> +		if err := r.Client.DeleteAllOf(ctx, &corev1.Service{},
Possibly even more disruptive than the `DataPlane` version: this can cause an established IP address for the `DataPlane` to be cycled. We have to try and protect the IP.

2022-07-28 19:15 UTC, jrsmroz commented on controllers/controlplane_controller.go
> +		return r.clusterRoleHasControlplaneOwner(e.ObjectOld)
Shouldn't this filter only the events that change the cluster role to state that we don't expect instead of all states?

2022-07-28 19:37 UTC, jrsmroz commented on controllers/controlplane_controller_watch.go
> +		log.FromContext(context.Background()).Error(
```go
// FromContext returns a logger with predefined values from a context.Context.
func FromContext(ctx context.Context, keysAndValues ...interface{}) logr.Logger {
	log := Log
	if ctx != nil {
		if logger, err := logr.FromContext(ctx); err == nil {
			log = logger
		}
	}
	return log.WithValues(keysAndValues...)
}
```
Will call
```go

func FromContext(ctx context.Context) (Logger, error) {
	if v, ok := ctx.Value(contextKey{}).(Logger); ok {
		return v, nil
	}

	return Logger{}, notFoundError{}
}
```

In the end, the global Log will be used anyway. 
I do not see any benefit over jus using this background thing over

```go
log.Log.Error( //...

```

2022-07-28 19:46 UTC, jrsmroz commented on controllers/gateway_controller.go
> +	dataplane, err := r.ensureDataPlaneForGateway(ctx, gateway, gatewayConfig)
You may want to pull the latest changes from main. Reconcile loop was totally redone when new conditions handling was added.

2022-08-03 23:35 UTC, rainest commented on controllers/controlplane_controller.go
> +		Owns(&appsv1.Deployment{}).
Can you elaborate on what we'd have less control over and what the awkward semantics are?

2022-08-04 14:25 UTC, shaneutt commented on controllers/controlplane_controller.go
> +		Owns(&appsv1.Deployment{}).
I think the main thing is that I like having direct access to the `Watch()` method present in the `controller.Controller` type, but this ultimately I don't think actually limits our control for our purposes. In retrospect and because this PR has been sitting for a long time, I'm going to consider this one resolved because I don't think we need to spend any further time on it as it's more of a nit, and because it's easy to change later if we run into any problems.

2022-08-05 17:04 UTC, rainest commented on controllers/controlplane_controller.go
> +		Owns(&appsv1.Deployment{}).
I'd still be interested in hearing what you've encountered in the past--you've got more controller-runtime experience than I do and this is the first time I've encountered `Owns()`, so it'd be useful to understand scenarios where you'd be inclined to use it but would need to add `Watch()` parameters beyond whatever the `Owns()` sets up on your behalf.

2022-08-12 15:30 UTC, mlavacca commented
Reverting this PR back to draft as it needs to be reworked in regards to the reduction over replacement strategy mentioned by Shane

2022-08-12 15:38 UTC, mlavacca commented on controllers/controlplane_controller.go
> -	}
I'm not sure I'm getting your point here, do you mean we should leave these requeues as they are?

2022-08-12 15:42 UTC, mlavacca commented on controllers/controlplane_controller_reconciler_utils.go
> +		if err := r.Client.DeleteAllOf(ctx, &appsv1.Deployment{},
Gotcha, I didn't consider this aspect. I'll dig in the `ReplicaSet` and `Pod` controllers to find if we can take inspiration for this pattern. If those changes will make this PR grow too much, I'll create follow-up issues.

2022-08-12 15:44 UTC, mlavacca commented on controllers/dataplane_controller_reconciler_utils.go
> +		if err := r.Client.DeleteAllOf(ctx, &appsv1.Deployment{},
Ok, I'll address this reduction problem first, as it has more priority than others.

2022-08-12 15:46 UTC, mlavacca commented on controllers/gateway_controller.go
> +	dataplane, err := r.ensureDataPlaneForGateway(ctx, gateway, gatewayConfig)
yeah, I'm handling tons of conflict, not funny 😞

2022-08-16 14:45 UTC, mlavacca commented
@shaneutt since the reduction over replacement strategy would make this PR kinda huge, I think it'd be better to reduce this PR's scope and not handling the situation in which more that one object exists. If you agree, I'll leave all the conditionals `if count > 1 {//do stuff}` and create a follow-up PR to resolve the reduction problem specifically. Does it work for you?

2022-08-19 10:38 UTC, mlavacca commented on controllers/controlplane_controller.go
> +		return r.clusterRoleHasControlplaneOwner(e.ObjectOld)
Since the ClusterRole is owned by the controlplane, we should watch for all its events (as vanilla Owns does). We could perform more granular filtering, but it is only a matter of optimization and out of this PR's scope. I wrote the reason behind this predicate in a comment, copying here:

```
// we need to get the old objects for cluster-wide resource updates to address
// cases in which the ownerReference is changed or deleted. If we use the newObject,
// we cannot infer the object owner, as there is no reference to it, and we'd lose
// the event that should trigger the creation of a new resource
```

2022-08-19 11:13 UTC, mlavacca commented
Here are a couple of follow-up issues:
* #182 
* #183

2022-08-19 14:52 UTC, shaneutt requested changes
Things are mostly looking good, but I have two explicit blockers:

* we should not be disabling cache for `Deployments` and `Secrets`, we need to try to find an alternative solution for this problem. I might be agreeable to doing a follow-up if it gets to big, but ultimately we shouldn't have this post alpha and if we can solve it now we should
* I don't see tests. Ideally we should add unit tests throughout. Also while I get the idea is that the integration tests should continue to pass, we should actually be adding integration tests where we intentionally delete and "de-own" objects and verify the replacement behavior is working correctly (and not creating too many, OR too little (none) replacements).

2022-08-19 14:52 UTC, shaneutt commented on controllers/controlplane_controller.go
> +	// the event that should trigger the creation of a new resource
:+1: I appreciate the comment here. I do wonder though if I may suggest a rewording that I think might be a bit more straightforward?

```suggestion
	// for owned objects we need to check if updates to the objects resulted in the
	// removal of an OwnerReference to the parent object, and if so we need to
	// enqueue the parent object so that reconcilation can create a replacement.
```

Just a thought, let me know your thoughts? Not a blocker, resolve at your own discretion.

2022-08-19 14:52 UTC, shaneutt commented on controllers/controlplane_controller.go
> +			builder.WithPredicates(clusterRoleBindingPredicate)).
Good comments! Everything we're doing here is nice and clear at a glance for future readers :+1:

2022-08-19 14:52 UTC, shaneutt commented on controllers/controlplane_controller.go
> +		return ctrl.Result{}, nil
might be worth a breadcrumb comment here for future readers:

```suggestion
		return ctrl.Result{}, nil // requeue will be triggered by the creation of the owned object
```

There's actually several places where something similar happens, I know it might seem excessive but I would personally just put a comment like this on each of them.

2022-08-19 14:52 UTC, shaneutt commented on controllers/controlplane_controller_watch.go
> +		return true
:+1: we need to keep this in mind going forward, it's kinda subtle: unless you get a type error, you pretty much just wanna return true for these kinds of filters _unless_ you are _certain_ the object is not relevant. This can help to reduce "stuck" behavior of the operator when a cluster API outage occurs by ensuring that the resource gets into the queue and will _eventually_ be reconciled when the API comes back to health.

2022-08-19 14:52 UTC, shaneutt commented on controllers/gateway_controller.go
> +		Complete(r)
I see you really like the other way of initializing the controller. Which is fine, but at this point let's just make sure we're consistent about this across the repo.

2022-08-19 14:52 UTC, shaneutt commented on controllers/utils.go
> +}
nit: this is a mutator, where the functions around it are retrievers. A really tiny thing, but I would suggest not grouping them together. Perhaps we can just place it right next to the other functions it calls with similar purpose?

Also (and I know this is most likely MY fault so I get the irony) it seems like we should actually put a verb on this function and the underlying functions: we put `get<thing` on functions that retrieve data from some given information, perhaps we should put `addLabelFor<thing>` for these three functions so it's more clear at a glance that it causes object mutation?

Really minor things, but could slightly improve readability.

2022-08-19 14:52 UTC, shaneutt commented on internal/manager/run.go
> +		},
This one is a bit tricky. At certain scales this will definitely cause undo stress on the API server, we've seen it in our other products with `Secrets` some people just have absolutely massive amounts of them. I appreciate your comments on this explaining the situation, albeit I might not be 100% clear on the issue:

We state here that the problem occurs when we create a `Deployment` (for instance), there's already another request for the parent object in the queue? Ideally what should happen is this:

1. we create the `Deployment`
2. we end reconcilation, _without_ requeuing
3. the creation of the `Deployment` results in the parent object being enqueued
4. reconcilation is re-entered and can reach the next step where it can find the `Deployment`

Are there problems with making this work? Am I missing something?

2022-08-22 07:46 UTC, mlavacca commented on controllers/gateway_controller.go
> +		Complete(r)
Yep, I changed the Gateway controller setup for this reason :) we should be consistent across the repo at this point.

2022-08-22 12:29 UTC, mlavacca commented on internal/manager/run.go
> +		},
I wasn't totally clear in the comment, let me add some more context. 
The situation you depicted as a bullet list reflects 100% what happens. It works 99% percent of the time (I never succeeded in triggering this error on my local machine), but under certain conditions (in CI at least 1 test fails every time, there is no specific failing test, and all of them fail randomly with the same reason) something strange  in the dataplane controller loop happens:
1. the mTLS secret is created by the dataplane controller, and the loop ends
2. the secret creation triggers another loop in the dataplane controller
3. the dataplane controller loop tries to retrieve the mTLS secret by label and `ownerRef`, but it fails. No mTLS secrets belonging to the dataplane are found in the cache.
4. as a result, another mTLS secret is created
5. Another reconciliation loop (triggered by the second mTLS secret creation) happens
6. the dataplane controller lists all the secrets owned by the dataplane, and two secrets are found. 
7. There is no recovery from this situation at the moment.

To have evidence of the issue, try searching for "found 2" in the integration test pipeline in this PR, and you'll see what I'm talking about. In CI, This happens very often with the dataplane secrets and sometimes with the dataplane deployment. If we disable the cache for Deployments and Secret, the tests succeed at 100%. 

I get that disabling the cache for those objects is a workaround to the problem, but I tried to figure out the root cause of the problem for a while without success. When we'll be able to recover from the situation in which two objects of the same type exist, we can re-enable the cache.

Furthermore, I totally understand that in a production environment with plenty of secrets, reading directly from the API server could create a heavy load on it, but since we are still working on a technical preview, do you still think it is unacceptable having this workaround for the moment?

2022-08-22 12:30 UTC, mlavacca commented
> I don't see tests. Ideally we should add unit tests throughout. Also while I get the idea is that the integration tests should continue to pass, we should actually be adding integration tests where we intentionally delete and "de-own" objects and verify the replacement behavior is working correctly (and not creating too many, OR too little (none) replacements).

I'm gonna add some tests

2022-08-22 18:47 UTC, shaneutt commented on internal/manager/run.go
> +		},
Talked about this one with @mlavacca in Slack: we're going to go with the cache disable option for the moment since we're still in an early alpha phase and it's OK to use this as a workaround for the time being. https://github.com/Kong/gateway-operator/issues/182 is the follow up to solve this wholesale before the next alpha release.

2022-08-22 18:50 UTC, shaneutt approved these changes
The new tests look adequate for now so that we avoid regressions :+1:

This seems like a good place to stop and merge, and as discussed we will continue the implementation in the follow-up issues we created here.

2022-08-22 18:51 UTC, merged