ci: Red Hat Scan registry
Kong/gateway-operator pull request #93
Opened 2022-07-19 11:13 UTC by jrsmroz

**What this PR does / why we need it**:

**Which issue this PR fixes**

**Special notes for your reviewer**:

**PR Readiness Checklist**:

Complete these before marking the PR as `ready to review`:

- [ ] the `CHANGELOG.md` release notes have been updated to reflect significant changes

2022-07-26 09:47 UTC, mflendrich commented on .github/workflows/nightly.yaml
> +          cache-to: type=local,dest=/tmp/.buildx-cache
This may be very ignorant, so please behold:

Does this setup ensure that layers are cached across subsequent CI runs?
This workflow uses `type=local` and no [actions/cache](https://github.com/Kong/kubernetes-ingress-controller/blob/e6c2c585252d5d569e4fa45930ac9701f216c2ff/.github/workflows/test.yaml#L25) to preserve the cache across runs.

There are two ways known to me to achieve this:
1. Use `actions/cache` to load & preserve the state of the layer cache,
2. Use [`type=gha`](https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md#cache-backend-api) (which I haven't tried myself before)

2022-07-26 09:47 UTC, mflendrich commented on .github/workflows/nightly.yaml
> +          echo "type=raw,value={{date 'YYYY-MM-DD'}}" >> $GITHUB_ENV
DRY: if we make `{{date 'YYYY-MM-DD'}}` a new variable in `env`, there will be no need for repeated template expansion.

2022-07-26 09:47 UTC, mflendrich commented on .github/workflows/nightly.yaml
> +          registry: scan.connect.redhat.com
Already available in the `RH_SCAN_REGISTRY` variable

2022-07-26 09:47 UTC, mflendrich commented on .github/workflows/nightly.yaml
> +              --certification-project-id=${{ secrets.RH_PROJECT_ID }}
Don't we want to run this before pushing? :thinking:

2022-07-26 09:57 UTC, jrsmroz commented on .github/workflows/nightly.yaml
> +              --certification-project-id=${{ secrets.RH_PROJECT_ID }}
No. It requires image to be pushed

2022-07-26 09:58 UTC, jrsmroz commented on .github/workflows/nightly.yaml
> +          echo "type=raw,value={{date 'YYYY-MM-DD'}}" >> $GITHUB_ENV
Sure. It was copied from KIC.

2022-07-26 13:48 UTC, shaneutt requested changes

2022-07-26 13:48 UTC, shaneutt commented on .github/workflows/nightly.yaml
> +          cache-to: type=local,dest=/tmp/.buildx-cache
It would appear the purpose of this cache is only for between tasks in this job, see the below build entries where the cache is pulled with `cache-from`.

2022-07-26 13:48 UTC, shaneutt commented on .github/workflows/nightly.yaml
> +          platforms: linux/amd64
Right this is what we discussed yesterday. I don't think we need to leave the comment with the multiple platforms in:

```suggestion
          # RedHat scan registry does not support multiarch images
          platforms: linux/amd64
```

However, what I DO think we should add here is a link to the relevant Redhat documentation which describes this limitation, that way future readers have some breadcrumbs to work with if they're trying to make changes to the platform support for this workflow.

2022-07-26 13:48 UTC, shaneutt commented on .github/workflows/nightly.yaml
> +          image: quay.io/opdev/preflight:stable
We're giving this third party privileged READ access to our Github secrets. I'm not familiar with this action but given that it's not a github or docker action, I would suggest it has greater than usual supply chain security implications. Ideally when using something like this we would separate it out into its own job and give it no secrets access, but that doesn't appear to be completely feasible given that we need to provide it with `RH_PYXIS_TOKEN`.

So my question is: is there any way we can _not_ use this action to fulfill the need?

2022-07-26 13:48 UTC, shaneutt commented on Dockerfile
> +# Refer to https://github.com/GoogleContainerTools/distroless for more details
Thanks for adding a link to distroless here, I think that will be helpful for future readers :+1:

2022-07-26 14:23 UTC, jrsmroz commented on .github/workflows/nightly.yaml
> +          platforms: linux/amd64
There is no doc entry for that. I've learned by experimenting and googling. scan registry refused to accept the multiarch image with internal server error 500, with no additional comments. By googlong I've learned that it's common problem, not all image registries support multiarch yet.

2022-07-26 14:26 UTC, jrsmroz commented on .github/workflows/nightly.yaml
> +              --certification-project-id=${{ secrets.RH_PROJECT_ID }}
Can be done. We can create a separate that uses the docker image provided. We do not need to use this action.

2022-07-26 14:27 UTC, jrsmroz commented on .github/workflows/nightly.yaml
> +          cache-to: type=local,dest=/tmp/.buildx-cache
As Shane said.

2022-07-26 14:37 UTC, shaneutt commented on .github/workflows/nightly.yaml
> +          platforms: linux/amd64
Well, I can't say I'm particularly surprised that they don't document this, it just fails. Ok then :shrug:

2022-07-26 15:32 UTC, jrsmroz commented on .github/workflows/nightly.yaml
> +          image: quay.io/opdev/preflight:stable
Can be done. We can create a separate that uses the docker image provided. We do not need to use this action. I need to be separate job thought, not a step in current job.

2022-07-26 16:50 UTC, shaneutt commented on .github/workflows/nightly.yaml
> +          image: quay.io/opdev/preflight:stable
Unless we have a strong reason then, I suggest we change this.

2022-07-26 16:52 UTC, jrsmroz commented on .github/workflows/nightly.yaml
> +          image: quay.io/opdev/preflight:stable
Sure. I will try custom action first. Then we can move it separate repo. The KIC will need it too.

2022-07-26 16:56 UTC, rainest commented on .github/workflows/nightly.yaml
> +          cache-to: type=local,dest=/tmp/.buildx-cache
Yeah, the goal here (in the original KIC version, at least) is that we only have to compile the binary once in the builder target, which is then re-used as the basis of both the distroless and UBI images. That generally always needs to change, since the goal is to test the new code that's been merged since the last one.

You could maybe optimize this a bit further to cache other parts across runs, but:
- You'd need to optimize the Dockerfiles first so that any static layers are done before anything that changes run to run.
- Your run times are still going to be dominated by the compile time.
 
There isn't actually much to optimize away, since basically all we do is compile, copy the binary in, and add a user. It'd be of more use if we did something slowish that may well persist between runs, like installing packages.

2022-07-26 18:57 UTC, jrsmroz commented on .github/workflows/nightly.yaml
> +          echo "type=raw,value={{date 'YYYY-MM-DD'}}" >> $GITHUB_ENV
@mflendrich fun fact, it's not really a date, it's a format string for and action: https://github.com/docker/metadata-action#date-format

2022-07-27 14:29 UTC, jrsmroz commented on .github/workflows/nightly.yaml
> +          image: quay.io/opdev/preflight:stable
@shaneutt With github action it looks like this: https://github.com/Kong/gateway-operator/pull/107/files (PR againts this PR)

Are you happy with that? If so we can export that action to separate kong repo and use it for KIC too.

2022-07-27 14:30 UTC, jrsmroz commented on .github/workflows/nightly.yaml
> +          cache-to: type=local,dest=/tmp/.buildx-cache
Acutually there was one bit missing:

```
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
```

2022-07-27 14:33 UTC, shaneutt commented on .github/workflows/nightly.yaml
> +          image: quay.io/opdev/preflight:stable
Yes I think that's good. Thanks for taking the extra time to do that :bow: 

I would like to move forward with that, but we can start by just plugging it in here.

2022-07-27 15:04 UTC, jrsmroz commented on .github/workflows/nightly.yaml
> +          image: quay.io/opdev/preflight:stable
Yeah. I will extract it to separate repo, so it can be reused, when I go back the KIC RH Certification.

2022-07-27 15:09 UTC, shaneutt approved these changes

2022-07-27 19:43 UTC, merged